### ISSUE TITLE
Remove experimental modules (was #276)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#16] opened 2014-02-27 15:33 UTC
_From [andreass...@gmail.com](https://code.google.com/u/102889613336421617108/) on January 26, 2010 12:46:37_

As soon as a module repository is ready, we should consider all modules, and move out some of the 
more experimental modules such as infocard to the repository.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=276_

**Comment by jaimeperez** [comment] 2015-01-15 18:15
This is a duplicate of #154. Since this issue is more generic than that one, and doesn't really specify the list of modules to remove, close this one and keep the new one.

**Closed by jaimeperez** 2015-01-15 18:15 UTC
Labels: duplicate, enhancement, imported, started
