### ISSUE TITLE
Compatibility with Laravel 9

### ISSUE THREAD

**Issue by sachin-acto** [simplesamlphp/simplesamlphp#1650] opened 2022-06-06 12:21 UTC
**Is your feature request related to a problem? Please describe.**
Since the symphony libraries are points to `5.*` versions, we are not able to use it with Laravel 9 for which min symphony version is `6.*`

**Describe the solution you'd like**
Dump the symphony version to `6.*`

**Comment by tvdijen** [comment] 2022-06-06 18:53
Duplicate of #1588

**Closed by tvdijen** 2022-06-06 18:53 UTC
