### ISSUE TITLE
getSelfURL() function returns URL with port number - improvement proposal based on RFC-2396

### ISSUE THREAD

**Issue by karolflis** [simplesamlphp/simplesamlphp#696] opened 2017-09-28 12:34 UTC
Hi guys.

This topic was somewhat touched in https://github.com/simplesamlphp/simplesamlphp/issues/651
I have gained more insight since then (and encountered same issue couple of times).

For reference I'll paste that line returning URL with port:
lib/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php
`771: return $protocol.$hostname.$port.$_SERVER['REQUEST_URI'];`

Issue: to pass compare check we would have to add (:80, :443) ports to our baseurlpaths. While sites on default ports don't present themselves with port number.

This has became a reoccurring issue for my company, we are patching same thing every new instance of application using simplesamlphp, because otherwise you get an error (you can see the error in the issue I have previously posted, link above).

This particular issue we are encountering every implementation of SAML, really. I have decided to give it a go and try to find general solution based on RFC.

Uniform Resource Identifiers (URI): Generic Syntax, Section 6 [http://www.rfc-base.org/txt/rfc-2396.txt](url)

> 6. URI Normalization and Equivalence
>
>   In many cases, different URI strings may actually identify the
>  identical resource. For example, the host names used in URL are
>   actually case insensitive, and the URL <http://www.XEROX.com> is
>   equivalent to <http://www.xerox.com>. In general, the rules for
>   equivalence and definition of a normal form, if any, are scheme
>   dependent. When a scheme uses elements of the common syntax, it will
>   also use the common syntax equivalence rules, namely that the scheme
>   and hostname are case insensitive and a URL with an explicit ":port",
>   where the port is the default for the scheme, is equivalent to one
>   where the port is elided.

In my opinion this make sense, there is no reason to append port number to the URL when you are using default port for that protocol like: http://example.com:80/ or https://example.com:443/

So for example could getSelfURL() function be modified to return URL string with port number for non default protocol ports?

Example returned strings:
http://example.com <- no port appended, because 80 is default port for protocol
https://example.com <- no port appended, because 443 is default port for protocol
http://example:8080 <- custom port, hence port number appended
etc.

Please ask any questions if this has been explained not clearly.

If this function (or functionality in general) could be improved/changed then it would be great and we would get rid of this issues we have for every instance.

**Comment by jaimeperez** [comment] 2017-10-10 13:39
Hi @karolflis!

While you are right in that it makes sense to skip the port if it's the standard one (and for the record, I'm absolutely not against that, as it'll be a quite simple fix), I think we should try to understand what the issue is here first. Where are you encountering this problem? Is it still the example you were giving in #651?

I'm asking because that should never happen. As I tried to explain there, the code you are having trouble with is run **only** when the current URL points to a script that's not part of SimpleSAMLphp but using it. This means if the current URL **is** a SimpleSAMLphp endpoint (as the Assertion Consumer Service endpoint you were giving as an example), then this code will **not** be executed, and therefore you shouldn't experience the issue you are experiencing.

This leads me to think that there might be some other issue with your setup, since if there was a bug here (other than explicitly adding default ports to the URL), I would expect lots of people to encounter it.

So, let's see if we can figure out what's going on here. First, is it the same example in #651 the one you are having trouble with? Secondly, how does your setup look like? Do you have TLS offloaded to a load balancer? What do you have in `baseurlpath`?

**Comment by karolflis** [comment] 2017-10-11 08:07
Hi Jaime.

Thanks for response.

Now I'm wondering too if there is something wrong with my setup. 

So, I have checked our SVN repository for patches with fix to that function I'm mentioning. (patch removing $port part in  lib/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php).

We have two instances.
1. Based on Moodle 3.1 and auth_saml2 plugin
2. Based on Totara_9 and auth_saml2 plugin 

(This is same plugin - Totara is a fork of Moodle, reusing its plugins etc. auth_saml2 plugin is built with code from your github) 
There is no loadbalancer in our environments.

And $baseurlpath is based on auth_saml2 plugin (wrapper config file) auth/saml2/config/config.php
`28: $wwwroot = $CFG->wwwroot;`
`34: 'baseurlpath'       => $wwwroot . '/auth/saml2/sp/'`

And $wwwroot hold just site plain URL (from $CFG->wwwroot - which is global setting from Moodle config.php), without anything special like port.
`$CFG->wwwroot   = 'https://<url>.ie';`

I might be wrong but maybe that description you can find getSelfURL() comments is somewhat misleading/outdated or changes its meaning. This is what I might be thinking because, you say that this part of code is getting used when something seriously goes wrong.
However when I check usages of getSelfURL(); with PHPStorm, I can find it in couple places, and it seems to me like mechanism of getting self url in various places.

/var/www/html/mahara1710/auth/saml/extlib/simplesamlphp/modules/saml/lib/IdP/SAML2.php
receiveAuthnRequest() function.
`250:  \SimpleSAML\Utils\HTTP::checkSessionCookie(\SimpleSAML\Utils\HTTP::getSelfURL());`

Or bit if code for memcached:
/var/www/html/mahara1710/auth/saml/extlib/simplesamlphp/www/authmemcookie.php

`100: // redirect the user back to this page to signal that the login is completed
101: \SimpleSAML\Utils\HTTP::redirectTrustedURL(\SimpleSAML\Utils\HTTP::getSelfURL());`

What are your thoughts? Let me know what more info you need.

**Comment by jaimeperez** [comment] 2017-10-12 13:01
Hi @karolflis!

Thanks for the detailed response. I'm a bit puzzled with your setup, but that's probably just my lack of knowledge of Moodle and its internals.

Is it possible that SimpleSAMLphp is accessed through Moodle instead of directly? Part of the installation instructions say that you need to setup an alias in your web server, pointing to the `www` directory of SimpleSAMLphp. There, we use `/simplesaml` as an example, though you can use whatever you want, of course. In your configuration, it looks like `$wwwroot/auth/saml2/sp/` is pointing to the `www` directory inside SSP's installation (that's at least what you are saying by setting the `baseurlpath` configuration option to that). However, your previous examples show the following URL:

`https://example.domain.com/auth/saml2/sp/saml2-acs.php/foobar`

This is troublesome. If `/auth/saml2/sp/` is your base URL path, there should be a `saml2-acs.php` file in `/var/www/html/mahara1710/auth/saml/extlib/simplesamlphp/www/`. However, there's no such file. In fact, that file is in `/var/www/html/mahara1710/auth/saml/extlib/simplesamlphp/modules/saml/www/sp/`, and as part of a module, it is intended to be accessed through the `module.php` script located in `/var/www/html/mahara1710/auth/saml/extlib/simplesamlphp/www/`. The URL should be something like `$wwwroot/auth/saml2/sp/module.php/saml/sp/saml2-acs.php`, but since it isn't, it makes me thing some dirty tricks are being done here to load SSP's scripts from outside, bypassing SSP's internal mechanisms.

The code in the method that's creating trouble for you depends on whether the URL corresponds to a script under the SimpleSAMLphp installation directory or not. If not, the code unconditionally adding the port is run, and that's when you get the port breaking the check for the destination of the SAML response you just obtained.

So, to summarise, either the `baseurlpath` configuration option is wrong (although in that case, I would expect everything to break) or SSP endpoints are being called from inside a third-party application, which shouldn't be done. If the latter, go back to SSP's installation guide and make sure you configure your web server with an alias pointing to the `www` directory as mentioned there. There's no need for third-party applications to intercept call's to SimpleSAMLphp, and in fact, they should avoid doing so as that could break things like in your case.

I'm closing the ticket for now, but feel free to keep the discussion if you don't think my assessment is correct. I will try to fix the code so that default ports aren't included in the URLs _guessed_, but still you should fix your setup as it doesn't look like a normal installation.

Hope this helps.

**Closed by jaimeperez** 2017-10-12 13:01 UTC
Labels: needsinfo

**Comment by karolflis** [comment] 2017-10-12 14:11
Hi @jaimeperez .

Oh my, your explanation is very well written and on point.

To clarify some points:
>However, your previous examples show the following URL:
>
>https://example.domain.com/auth/saml2/sp/saml2-acs.php/foobar
>
>This is troublesome. If /auth/saml2/sp/ is your base URL path, there should be a saml2-acs.php file in /var/www/html/mahara1710/auth/saml/extlib/simplesamlphp/www/. However, there's no such file. 

You are right. It gets included with:
`35: require($CFG->dirroot.'/auth/saml2/extlib/simplesamlphp/modules/saml/www/sp/saml2-acs.php');`
from this level:
`https://example.domain.com//auth/saml2/sp/saml2-acs.php`


>or SSP endpoints are being called from inside a third-party application, which shouldn't be done. If the latter, go back to SSP's installation guide and make sure you configure your web server with an alias pointing to the www directory as mentioned there.

Third-party application in this context is auth_saml2 plugin, and you are right again and because the files get included via this plugin there is no need to use webserver alias.


>There's no need for third-party applications to intercept call's to SimpleSAMLphp, and in fact, they should avoid doing so as that could break things like in your case.

As a matter of fact, there are 3rd party applications including simplesamlphp (as in mentioned plugin to moodle/totara/mahara) and people are using it. It is somewhat simplier to set up SAML SSO, thanks to that. (And believe me having to work with SSP without any previous experience has a steep learning curve, we even have a saying here, going: 'Couple more years, and we are going to finally fully understand simplesaml' :)

Actually now I see that https://moodle.org/plugins/auth_saml2 is maintained by Catalyst IT (mentioned in https://simplesamlphp.org/support) so it seems they made it possible?

> I will try to fix the code so that default ports aren't included in the URLs guessed, but still you should fix your setup as it doesn't look like a normal installation.

This will be a solution to this issue, which I would much appreciate and maybe some other people too.
Thanks again, I'm still learning about SSP so maybe we will be in touch :)

**Comment by karolflis** [comment] 2017-10-13 09:22
Just a quick question, how I can track or check progress on the change to this function you will hopefully implement?:)

**Comment by jaimeperez** [comment] 2017-10-13 14:48
Hi @karolflis!

Would you mind applying the following patch and telling me if it works for you?

```diff --git a/lib/SimpleSAML/Utils/HTTP.php b/lib/SimpleSAML/Utils/HTTP.php
index fd01223..e31c088 100644
--- a/lib/SimpleSAML/Utils/HTTP.php
+++ b/lib/SimpleSAML/Utils/HTTP.php
@@ -780,13 +780,16 @@ class HTTP
              * It doesn't matter which one of those cases we have. We just know we can't apply our base URL to the
              * current URI, so we need to build it back from the PHP environment.
              */
+            $https = self::getServerHTTPS();
             $protocol = 'http';
-            $protocol .= (self::getServerHTTPS()) ? 's' : '';
+            $protocol .= $https ? 's' : '';
             $protocol .= '://';

             $hostname = self::getServerHost();
             $port = self::getServerPort();
-            return $protocol.$hostname.$port.$_SERVER['REQUEST_URI'];
+            return $protocol.$hostname.
+                (($https && $port !== ':443') || (!$https && $port !== ':80') ? $port : '')
+                .$_SERVER['REQUEST_URI'];
         }

         return self::getBaseURL().$rel_path.substr($_SERVER['REQUEST_URI'], $uri_pos + strlen($url_path));
```

Still, as I said, you should fix your setup. What the plugin is doing is wrong. It shouldn't be serving SimpleSAMLphp's scripts through its own scripts by calling `require()`. I get that it's easier if the plugin does stuff for you, but you still need to configure things in SimpleSAMLphp and your setup, so you still need to read the documentation, and then you could configure the alias as described in the documentation and make sure nothing interferes with the execution of SSP.

**Comment by jaimeperez** [comment] 2017-10-16 09:38
Hi again @karolflis!

Now that I look closer into this while trying to solve another issue, I noticed the patch is superfluous and the problem you are experiencing cannot be due to this code. `SimpleSAML\Utils\HTTP::getServerPort()` will also call `SimpleSAML\Utils\HTTP::getServerHTTPS()` to determine if the protocol used is HTTPS or HTTP, and depending on that and the port observed, return the port number with a colon prepended, or an empty string if the port is the default one for the current protocol. [Here's the code](https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.14/lib/SimpleSAML/Utils/HTTP.php#L99-L112).

Given that `getServerHTTPS()` will always return the same, it's not possible that you get a URL generated with `https` as the protocol and `:443` in the port. When you point to the line where the function returns (supposedly) the wrong URL, you mentioned line 771 both here and in the other issue. However, I can't see that line having such a number in any stable version of SimpleSAMLphp, so I'm wondering what version you are using.

**Comment by karolflis** [comment] 2017-10-16 12:52
Hi again @jaimeperez 

It was/is 1.14.10 version, but pasted line may come from other one (we have couple of setups), I dont know exactly from which on I've copied it. Anyway based on your on point comments it let me to look at these functions and look for culprit.

I think I have figured it out.
We use reverse proxy on shared hosting servers. Meaning default $_SERVER['SERVER_PORT'] is always 80.
However we manually set global variables for every Moodle php file, via config.php (which gets included to every file):
```
if(substr($CFG->wwwroot,0,5) == 'https') {
    $_SERVER['SERVER_PORT'] = 443;
    $_SERVER['HTTPS'] = '1';
}
```
var dump of $_SERVER:
```
 ["SERVER_PORT"]=>
  int(443)
```

And that works for us.

But notice, we set it to 443 as **int.**

And check in this function is based on comparison identical operator (===) vs **string**, which evaulates to true and then it can return 443 from if statement :)
```
private static function getServerPort()
    {
        $port = (isset($_SERVER['SERVER_PORT'])) ? $_SERVER['SERVER_PORT'] : '80';
        if (self::getServerHTTPS()) {
            if ($port !== '443') {
                return ':'.$port;
            }
        } else {
            if ($port !== '80') {
                return ':'.$port;
            }
        }
        return '';
    }
```

I have yet to test it, but it seems to be it.

Do you consider changing === comparison to == in this function or is it out of question?
We can change it on our side no problem. 
But there may be more users with port set to **int** in the future and this would come to play.

**Comment by tvdijen** [comment] 2017-10-16 13:09
Have you considered setting it as a string?
`$_SERVER['SERVER_PORT'] = '443'`

Because that's what it is if you don't mess with it:  a string...

**Comment by karolflis** [comment] 2017-10-16 13:18
> We can change it on our side no problem.

Yes, we will have to change it anyway, even if @jaimeperez  would implement change to comparison operator it only would be in future release.

**Comment by christianheimann** [comment] 2019-12-24 09:07
Just as a note here to this issue. I fell on the same problem that the port was set with :80, but the cause was the exposed port in a containerized environment with kubernetes. The exposed container was 80, but all connection went over https – so the existing check could not return an empty string. This may help others as well…

**Comment by tvdijen** [comment] 2019-12-24 09:38
So you've ended up with `https://example.org:80/simplesaml`? Then the method did exactly what it's supposed to do, right?

**Comment by christianheimann** [comment] 2019-12-24 09:46
Yes, exactely. The method works as it should; so ending up with :80 is an indicator for careless environment configuration.
