### ISSUE TITLE
Logout fails after passive authentification

### ISSUE THREAD

**Issue by bricev** [simplesamlphp/simplesamlphp#415] opened 2016-07-05 09:51 UTC
We use `simplesamlphp` to help users use an ADFS account to log in our PHP application.

Active login works perfectly: users click on a button we generate with the following code: 
```php
<?php $saml = new \SimpleSAML_Auth_Simple('default-sp'); ?>
<a href="<?php echo $saml->getLoginURL() ?>">Use ADFS to log me</a>
```
By using this way to login, logout works like a charm.

On the other hand, we detect the first time a user connects to our application to attempt a passive authentication with the following code :
```php
$saml = new \SimpleSAML_Auth_Simple('default-sp');
$saml->login([
      'isPassive' => true,
      'KeepPost'  => false,
      'ReturnTo'  => $returnUrl,
      'ErrorURL'  => $returnUrl,
]);
```
Authentication also works perfectly just like active login. 
But then when the user wants to logout, we have following error :

> SimpleSAML_Error_NoState: NOSTATE
> 
> Backtrace:
> 2 /path/to/simplesamlphp/lib/SimpleSAML/Auth/State.php:263 (SimpleSAML_Auth_State::loadState)
> 1 /path/to/simplesamlphp/modules/saml/www/sp/saml2-logout.php:67 (require)
> 0 /path/to/simplesamlphp/www/module.php:127 (N/A)

As logout works fine with active authentication, then why do I have such an error when users log passively?

Note 1 - users seems to be actually logged out dispite the error message.
Note 2 - I use MySQL to manage sessions (I had too many issues with local session storage). 

Any help would be (much) appreciated :)

**Comment by jaimeperez** [comment] 2016-07-05 10:55
Hi @bricev!

This is an issue tracker, not a support forum. Therefore, unless you are completely certain that this is a bug and not a misconfiguration or wrong usage, you should use the [mailing list](https://groups.google.com/forum/#!forum/simplesamlphp) to ask for support, where there are many people that could help you out.

I'm closing the issue for now, but if you confirm this as a bug, please just tell me and I'll immediately reopen it.

**Closed by jaimeperez** 2016-07-05 10:55 UTC

**Comment by jaimeperez** [comment] 2016-07-05 11:22
By the way! Make sure to include the logs, if possible, for both the IdP and the SP, as well as to specify how are you performing logout.

**Comment by bricev** [comment] 2016-07-05 11:40
I understand your concern, I have to say I'm no expert...

For both `active` and `passive` login, I use this code to log users out :
```php
$saml = new \SimpleSAML_Auth_Simple('default-sp');
if ($saml->isAuthenticated()) {
    $this->redirect($saml->getLogoutURL()); // Method redirect() does a proper redirection
}
```
... which works fine unless users are passively authenticated. This makes me think its a bug.

Here are the logs I found corresponding to this specific error :
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] Session: doLogout('default-sp')
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] Session: 'default-sp' not valid because we are not authenticated.
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] Saved state: '_185d1d08c5b4925cebd4e46222aaebae1d592fff6f'
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] Sending message:
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] <samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_5146943d9e7b55269a1a58e1e4e6694567690d4105" Version="2.0" IssueInstant="2016-07-05T09:42:50Z" Destination="https://auth.******.net/adfs/ls/">
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1]   <saml:Issuer>https://preproduction.app.******.net/simplesaml/module.php/saml/sp/metadata.php/default-sp</saml:Issuer>
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1]   <saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">app@ad.******.net</saml:NameID>
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1]   <samlp:SessionIndex>_7b0ba2ac-294c-4cf7-8280-b68dbb7e6f03</samlp:SessionIndex>
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] </samlp:LogoutRequest>
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] Redirect to 1062 byte URL: https://auth.******.net/adfs/ls/?SAMLRequest=fZJPa9wwEMW%2FitFdtuz4z1rsmhaWwkLaQ1N66CWMrXHXIMuqZgzpt6%2FszUKaQ47zNL%2F3ZgYdCWbr9ePye1n5O%2F5ZkTh5ma0jvb%2BcxBqcXoAm0g5mJM2Dfvr89VEXqdI%2BLLwMixVvkI8JIMLA0%2BJEcjmfxHOVl3VbPpgWm76qirqFHKoD5lhiHR%2BquqlbZcpcVSL5iYEieRLRKOJEK14cMTiOksprqRqpqh%2Bq1WWhK%2FVLJOe4zeSAd%2BrK7ElnGax8Ta84pGPIwIyUWcpEd9xm17tp6O6tPmBc0azD5pDGwsLfO0rT7C1uVDbHFoupv%2Fpsr8lnMzIYYNhFgyOsliX5Y%2FY25pb5LR7pck6%2BLGEG%2Fvh6mzIZOe6tmgM4mtCx6MDsaad%2BAOJPYF5HfA27%2Bd%2FCvH5C2x84cQZfuuemVz0UMMiiLQdZDmMjD8VXsb4%2BmL5vsB7Vw83mHXkX%2F%2Fs43T8%3D&RelayState=_185d1d08c5b4925cebd4e46222aaebae1d592fff6f&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=bjx2VpBI2mzgAoEBbgGzaDgcICyKMMa3BnwWIoOVJf6VQHJe%2Bcq96kSaPApbzW3d7wYgDdicDnAsc%2F8%2FNWbXcPOOqBBrI%2FSv%2F3jnDnlSsFBGnntgcjoDDlXLCL2N1HP0TT2VM%2FGh%2FjPMNURpkHYr92bKBD1Kq3tw%2FiqsCgt6FWXMWpe9e4dVdVMTbN7CQ9joD3YP5YX91OILSY8e0Ebgg%2ByZIsTs7SKOywXdSHdl9j9Mg8gDroz0MJLF0OaqRQOEDQQj3BbwmrPSHLQMS5PBR1ZrsuhBeA4MKOWuebn0%2BFNfrA7I0yeI9nmgFHruwvoBkvdfniA2HfN%2Fy%2Bfq1Cf97A%3D%3Darray (
> )
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] Deleting state: '_185d1d08c5b4925cebd4e46222aaebae1d592fff6f'
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] Received message:
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] <samlp:LogoutResponse xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="_d1ea1a65-353d-49b5-bdb4-2865c25a93c4" Version="2.0" IssueInstant="2016-07-05T09:42:50.478Z" Destination="https://preproduction.app.******.net/simplesaml/module.php/saml/sp/saml2-logout.php/default-sp" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="_5146943d9e7b55269a1a58e1e4e6694567690d4105">
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1]   <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://auth.******.net/adfs/services/trust</Issuer>
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1]   <samlp:Status>
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1]     <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1]   </samlp:Status>
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] </samlp:LogoutResponse>
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] Loading state: '_185d1d08c5b4925cebd4e46222aaebae1d592fff6f'
> Jul 05 11:42:51 simplesamlphp DEBUG [798e3dd3f1] Session: 'default-sp' not valid because we are not authenticated.
> Jul 05 11:42:51 simplesamlphp DEBUG [798e3dd3f1] Session: 'default-sp' not valid because we are not authenticated.
> Jul 05 11:42:51 simplesamlphp ERROR [798e3dd3f1] SimpleSAML_Error_NoState: NOSTATE
> Jul 05 11:42:51 simplesamlphp ERROR [798e3dd3f1] Backtrace:
> Jul 05 11:42:51 simplesamlphp ERROR [798e3dd3f1] 2 /path/to/simplesamlphp/lib/SimpleSAML/Auth/State.php:263 (SimpleSAML_Auth_State::loadState)
> Jul 05 11:42:51 simplesamlphp ERROR [798e3dd3f1] 1 /path/to/simplesamlphp/modules/saml/www/sp/saml2-logout.php:67 (require)
> Jul 05 11:42:51 simplesamlphp ERROR [798e3dd3f1] 0 /path/to/simplesamlphp/www/module.php:127 (N/A)
> Jul 05 11:42:51 simplesamlphp ERROR [798e3dd3f1] Error report with id 9a914e70 generated.
> Jul 05 11:42:51 simplesamlphp DEBUG [798e3dd3f1] Template: Reading [/path/to/simplesamlphp/dictionaries/errors]
> Jul 05 11:42:51 simplesamlphp DEBUG [798e3dd3f1] Template: Reading [/path/to/simplesamlphp/modules/core/dictionaries/no_state]
> Jul 05 11:42:51 simplesamlphp DEBUG [798e3dd3f1] Received message:
> Jul 05 11:42:51 simplesamlphp DEBUG [798e3dd3f1] <samlp:LogoutResponse xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="_7b110a56-1396-4899-a931-ddc648698b4c" Version="2.0" IssueInstant="2016-07-05T09:42:51.510Z" Destination="https://preproduction.app.******.net/simplesaml/module.php/saml/sp/saml2-logout.php/default-sp" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="_5146943d9e7b55269a1a58e1e4e6694567690d4105">
> Jul 05 11:42:51 simplesamlphp DEBUG [798e3dd3f1]   <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://auth.******.net/adfs/services/trust</Issuer>
> Jul 05 11:42:51 simplesamlphp DEBUG [798e3dd3f1]   <samlp:Status>
> Jul 05 11:42:51 simplesamlphp DEBUG [798e3dd3f1]     <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Requester"/>
> Jul 05 11:42:51 simplesamlphp DEBUG [798e3dd3f1]   </samlp:Status>
> Jul 05 11:42:51 simplesamlphp DEBUG [798e3dd3f1] </samlp:LogoutResponse>
> Jul 05 11:42:51 simplesamlphp WARNING [798e3dd3f1] Unsuccessful logout. Status was: exception 'sspmod_saml_Error' with message 'Requester' in /path/to/simplesamlphp/modules/saml/lib/Message.php:392
> Stack trace:
> #0 /path/to/simplesamlphp/modules/saml/www/sp/saml2-logout.php(64): sspmod_saml_Message::getResponseError(Object(SAML2_LogoutResponse))
> #1 /path/to/simplesamlphp/www/module.php(127): require('/path/to/s...')
> #2 {main}
> Jul 05 11:42:51 simplesamlphp DEBUG [798e3dd3f1] Loading state: '_185d1d08c5b4925cebd4e46222aaebae1d592fff6f'
> Jul 05 11:48:05 simplesamlphp DEBUG [798e3dd3f1] Session: 'default-sp' not valid because we are not authenticated

**Comment by jaimeperez** [comment] 2016-07-05 12:21
Hi,

According to the logs, it's not a bug, but your logout script or ADFS misbehaving. Once you invoke the script, logout works fine, as you can observe by the SAML logout response with status `urn:oasis:names:tc:SAML:2.0:status:Success`. The last log line for that logout flow is this one:

```
> Jul 05 11:42:50 simplesamlphp DEBUG [798e3dd3f1] Loading state: '_185d1d08c5b4925cebd4e46222aaebae1d592fff6f'
```

However, as you can see, you receive a second logout response from ADFS, this time being an error, indicated by the status `urn:oasis:names:tc:SAML:2.0:status:Requester`.

Since SimpleSAMLphp did not send a logout message, it could either be your script triggering logout directly at the IdP in a non-standard way (for example redirecting to a URL in ADFS that starts logout there), or the IdP itself misbehaving.

In any case, I've just replicated your use case and confirmed that it works fine with the latest stable release, so I'm afraid this is not a bug in SimpleSAMLphp but in your setup.

**Comment by bricev** [comment] 2016-07-06 09:46
Your answer helped me find a solution.
Thank you so much and sorry for posting a support message here.

**Comment by jaimeperez** [comment] 2016-07-07 07:48
No problem @bricev!

Could you please explain what was the root of the issue you were experiencing? That way if anyone else encounters the same issue and reaches here, they would be able to fix it.

Thanks!

**Comment by bricev** [comment] 2016-07-11 13:14
I only have a partial understanding of what happened.
For some reasons, the framework I'm using to develop our application was redirecting users back to the `logout` routing. The `action` corresponding to this route should be handling the fact users have no more session and the piece of code that log out from SSO should not be executed... but it was anyway. 

All I did was to provide another URL as callback to the `$saml->getLogoutURL()` method.

Thanks again for the help, next time I'll ask for support in your mailing list :)
