### ISSUE TITLE
Errors cant render due to Translator not being initialised.

### ISSUE THREAD

**Issue by wisebaldone** [simplesamlphp/simplesamlphp#1647] opened 2022-06-02 06:44 UTC
An early exit on here https://github.com/simplesamlphp/simplesamlphp/blob/da0df94ab05da52ce27ab7c2a360567046bf03b2/lib/SimpleSAML/Locale/Localization.php#L293 stops the translator from being used in line https://github.com/simplesamlphp/simplesamlphp/blob/da0df94ab05da52ce27ab7c2a360567046bf03b2/lib/SimpleSAML/Locale/Localization.php#L261

**Comment by tvdijen** [comment] 2022-06-02 07:14
Duplicate of https://github.com/simplesamlphp/simplesamlphp/issues/1592

We will release a bugfix in v1.19.6 shortly.  Thanks for reporting!

**Closed by tvdijen** 2022-06-02 07:14 UTC
Labels: duplicate
