### ISSUE TITLE
Don't require an IdP to return a NameID (Was issue 507)

### ISSUE THREAD

**Issue by davidmeredith** [simplesamlphp/simplesamlphp#143] opened 2015-01-12 14:51 UTC
My IdP does not return a NameID in the Subject of the response which causes exception: "Missing saml:NameID or saml:EncryptedID in saml:Subject".  This is an issue as IdPs don't have to set a NameID in the Subject if the Idp does not support the single logout profile. 
Was issue #507:  https://code.google.com/p/simplesamlphp/issues/detail?id=507

**Comment by thijskh** [comment] 2016-08-04 15:23
I believe this has been fixed in simplesamlphp/saml2@8a83fc81aa74dd0ed085e397ffaf1b676994dc42. As soon as this is in a saml2 release which is imported by simplesamlphp, this issue will be resolved.

**Comment by jayaprakashk** [comment] 2016-09-28 12:11
![saml_xml](https://cloud.githubusercontent.com/assets/6213414/18912915/a25b7edc-85a2-11e6-83dd-aea248e353cb.png)
Exception: Missing <saml:NameID> or <saml:EncryptedID> in <saml:Subject>.
Plz help me

**Comment by thijskh** [comment] 2016-09-28 12:42
@jayaprakashk This is not a support forum. Please do not post support questions here. The short answer to your question is that the IdP does not send a NameID in its assertion. If you need further help please ask at the mailing list.

**Comment by jayaprakashk** [comment] 2016-09-28 12:44
can you send mail id plz

**Comment by mfprimo** [comment] 2017-04-14 11:40
Hi,
  the fix has a severe side-effect: in modules/saml/www/sp/saml2-acs.php line 190

`sspmod_saml_SP_LogoutStore::addSession($sourceId, $nameId, $sessionIndex, $logoutExpire);
`
fails without any feedback (blank page, no message in log) if $nameId is null.

**Comment by thijskh** [comment] 2017-04-14 11:48
What fix? And why would it fail that way? On which line of that method? Are you sure you have your error reporting configured correctly?

**Comment by mfprimo** [comment] 2017-04-14 12:02
The fix mentioned above https://github.com/simplesamlphp/saml2/commit/8a83fc81aa74dd0ed085e397ffaf1b676994dc42

ACS endpoint fails at least in sspmod_saml_SP_LogoutStore::addSession()

`		/* Normalize NameID. */
		ksort($nameId);
`

but I think the problem is not that if fails silently, but that if NameID is null, no Logout Request is possible.
I think sspmod_saml_SP_LogoutStore::addSession() should be skipped for empty NameIDs

**Comment by tvdijen** [comment] 2017-04-14 13:35
That has already been fixed in the master-branch

**Closed** 2018-05-10 13:40 UTC
