### ISSUE TITLE
endless redirection loop when memcache server is down

### ISSUE THREAD

**Issue by spaceone** [simplesamlphp/simplesamlphp#264] opened 2015-09-29 13:18 UTC
If either the memcache PHP extension is not installed or the server is down one ends up in a redirection loop.
This loop should be detected and a error message should be presented to the client.

Memcache::addServer provides a $failure_callback parameter, which might help.
http://php.net/manual/en/memcache.addserver.php

Very nice would be a fallback to PHP sessions if the memcache servers are failing.

**Comment by stephaun** [comment] 2015-10-03 04:44
I am also experiencing a redirection loop--although not entirely sure if our problem is the same.
Immediately after installation (and some tweaking of the webserver config) I can access ``` myserver.com/simplesaml/module.php/core/frontpage_welcome.php``` just fine. However trying to login by clicking the "Login as administrator" link invokes an infinite redirection.

I'm on a basically bare EC2 Ubuntu 14.04 instance, running the only HHVM with NGINX.
``` echo "<?php print_r(get_loaded_extensions()); ?>" | php ```
This command returns an array containing ```memcache``` and ```memcached```, so I guess the extension is properly loaded. Additionally, running ```ps aux | grep memcache``` seems to work correctly.
Please forgive me as I have never really used memcache before, just thought I would add my 2 cents.

**Comment by stephaun** [comment] 2015-10-03 07:03
Okay after a few hours of frustration and about 5 test EC2 servers later, I have determined that my issue must be strictly with HHVM. Here is a rough overview of my tests:
-- Infinite redirection when run on Ubuntu 14.04 with HHVM and NGINX.
-- Infinite redirection when run on Ubuntu 14.04 with HHVM and Apache.
-- Works fine when run on bare Ubuntu 14.04 with "lamp-server^" package (php as apache module).
-- Works fine when run on Ubuntu 14.04 with Apache setup to pass requests to PHP with FCGI exact same way as HHVM ie: 
``` ProxyPassMatch ^/simplesaml/(.*\.php(/.*)?)$ fcgi://127.0.0.1:9000/var/www/simplesamlphp/www/$1 ```

This is irritating but I suppose I can make it work by having my main site run HHVM on port 9000 and the vanilla PHP run over FCGI on port 9001.

Sorry to hijack this issue thread, but I noticed that in my testing memcache actually had nothing to do with my issue.

**Comment by thijskh** [comment] 2015-10-06 14:57
The behaviour described by OP indeed happens when all memcache servers are down. This happens because Memcache::get returns false if the key is not found OR the server is down.

Perhaps the addServer callback function could be used to mark a server as failed, and then the SimpleSAML\Memcache::get() can bail out if all servers have been marked as failed.

**Comment by jaimeperez** [comment] 2015-10-23 08:21
Thanks for the report and the followup, guys!

I'll take a look into this ASAP. It's definitely not reasonable to get an infinite redirection loop if all the memcache servers are down.

**Comment by jaimeperez** [comment] 2015-10-26 17:00
Hi again!

This is weird, as I'm unable to reproduce the problem as you are reporting it. I get errors if all the memcache servers are down, but definitely not an endless loop. Can you share the settings you have used to reproduce this issue? Also, are you testing against master or a stable version?

I have a patch that addresses the issues, but I want to be really cautious here since it messes up with a lot of stuff that's quite delicate. This reminds me we need to get rid of the loops we have when loading sessions and logging messages meanwhile.

**Comment by spaceone** [comment] 2015-10-26 17:04
I am using simplesamlphp 1.13.2-1 - I can provide settings tomorrow otherwise I could also apply your patch and test it.

**Comment by jaimeperez** [comment] 2015-10-26 21:31
Thanks @spaceone! I'll try to reproduce the behaviour in 1.13.2. That will probably be easier than having you apply the patch on top of that, since a few things have changed and the patch will definitely not apply directly.

In any case, it would be nice if you could try it on top of master with your setup, and see if it helps.

**Comment by spaceone** [comment] 2015-10-27 12:33
The error still applies in master during authentication in SSOService.php.

**Comment by jaimeperez** [comment] 2015-10-27 12:41
Thanks! Now I've been able to reproduce it. I was testing with the front page, and there it just continues and creates a new session.

I'm about to commit a fix for this, which also puts some order in the mess we have today with sessions and logs. It works for me, but would you mind testing it out?

**Closed** 2015-10-27 12:42 UTC
Labels: bug, high, started

**Comment by jaimeperez** [comment] 2015-10-27 12:47
Oh, by the way!

Defaulting to PHP sessions is a bit more complicated. Since this is something that you configure, selecting **one or the other**, we cannot just fallback to the PHP session handler, so we would need to provide support for it directly in the Memcache session handler.

Additionally, that would give a couple more issues:

* When all the memcache servers are down, if you fallback to PHP sessions and you have more than one web servers running SimpleSAMLphp, you could end up with a mess if you have load balancing between them.
* You would also need to detect when the memcache servers are back, and dump the PHP sessions there. Otherwise, when looking for the session it won't be found.

So it would be nice, but it's quite complicated and needs a lot of thought and work on top of it, unfortunately...

**Comment by thijskh** [comment] 2015-10-27 12:56
The fix works for me.

I would also not prefer the fallback. The admin has configured memcache for a reason. If it doesn't work and falls back to something else, it hides the fact that the preferred configuration is broken and is potentially very confusing for users and admins.

**Comment by spaceone** [comment] 2015-10-27 14:15
This works nice! Thank you!
You can add a trailing dot to "Please try again in a few minutes".

**Comment by jaimeperez** [comment] 2015-10-28 09:22
Done!

Thank you both for testing this. I think we'll need to keep testing this extensively, as the changes are important and in a critical part. Please let me know if you notice any weird behaviour or side effects after this commit.
