### ISSUE TITLE
Can we have the exception message in the server log please?

### ISSUE THREAD

**Issue by murraycollingwood** [simplesamlphp/simplesamlphp#961] opened 2018-10-09 20:28 UTC
In the PHP error log:
```
Oct 10 06:10:54 simplesamlphp ERROR [8e9f2cf829] SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Oct 10 06:10:54 simplesamlphp ERROR [8e9f2cf829] Error report with id 6f883223 generated.
```

The report sent to the user trying to login however includes the exception message.  For example:
```
Caused by: Exception: saml20-idp-remote/'http://abc.def.au/adfs/services/trust': Unable to load certificate/public key from file "/home/sobs/cert/saml/ajfrs7sfhwk27dsjs.cer".
```

Can we have this exception message included in the PHP error log please?

Cheers
Murray

**Comment by tvdijen** [comment] 2019-08-29 10:01
This is a duplicate of #1002 - keeping that one

**Closed by tvdijen** 2019-08-29 10:01 UTC
