### ISSUE TITLE
Please tag commit #8c6ee7dd6a6c20e106c4d92603bdf849b667713b with some tag

### ISSUE THREAD

**Issue by tadasrimkus** [simplesamlphp/simplesamlphp#1825] opened 2023-07-12 15:35 UTC
I understand that this is work in progress, but there are people who are trying to use this for testing/fixing support in Drupal 10 (which uses symfony 6) and currently the most stable commit is  #8c6ee7dd6a6c20e106c4d92603bdf849b667713b

I will attach whole issue here https://www.drupal.org/project/simplesamlphp_auth/issues/3349278
Here's the current simplesamlphp packages that are used in working version
```
    "drupal/simplesamlphp_auth": "^4",
   ....
    "simplesamlphp/saml2": "v5.0.0-alpha.8",
    "simplesamlphp/simplesamlphp": "dev-master#8c6ee7dd6a6",
    "simplesamlphp/simplesamlphp-module-adfs": "v3.0.0-rc1",
 ```
 
 Thank you for tagging `simplesamlphp/simplesamlphp-module-adfs` to `v3.0.0-rc1` on the right commit, because previously master was used and now updating master is impossible due to recent changes in requirements.
 
 If we could use tagged version of this, alpha, beta, rc or whatever you think is the best it would still help a lot for anyone trying to get a semi stable setup for simplesamlphp in Drupal 10 instances.
 
 Thank you

**Comment by nitesh-voya** [comment] 2023-07-26 06:21
We also need this in our project as drupal 9 is reaching EOL in November 2023.  And this is one of our major functionality

**Comment by tvdijen** [comment] 2023-07-27 15:59
You're already tagging the commit in your composer-file.. Why would you need a version-tag? It doesn't add anything.

It's really unfortunate (to say the least) that Drupal decided to skip the entire Symfony 5.4 LTS version... I get that it is an issue for you, but we follow Symfony LTS and do not have the capacity to keep up with the latest/newest stuff of everything in the ecosystem that relies on SimpleSAMLphp. Symfony 5.4 is supported until Nov '25, so we really have no incentive to rush things..

**Comment by Berdir** [comment] 2023-07-28 06:05
A commit tag *only* affects the local checkout, composer can't do dependency resolution based on a commit, it will always look at latest dev-master and then afterwards switch to the desired commit. So a tag, e.g. an unstable0 or some suffix like that would definitely make a difference.

> Symfony 5.4 is supported until Nov '25, so we really have no incentive to rush things..

That's a bit over two years. two years is _not_ a lot of time. That's exactly why Drupal 10 skipped Symfony 5, because it would only leave two years between Drupal 9 EOL (Symfony 4 based, EOL Nov 23). Looking at https://packagist.org/packages/simplesamlphp/simplesamlphp#v2.0.0-beta.1, it took more than a year to go from beta to stable. So if it will be the same for v3 and assuming that you'd release beta now, your users would then have about a year to switch to v3 before v2 becomes unsupported.

That is again not a lot of time. If you look at https://packagist.org/packages/simplesamlphp/simplesamlphp/stats, it's been ~6 months since simplesamlphp v2 released and v2 only has 200 daily installs vs the 4k that v1 still has.

**Comment by tvdijen** [comment] 2023-07-30 19:04
> So if it will be the same for v3 and assuming that you'd release beta now, your users would then have about a year to switch to v3 before v2 becomes unsupported.

The reason for this was carrying over 10 years of legacy and technical debt and not enough human resources.. We will not let that happen again.

Somewhere over the next couple of days we will be releasing v2.1 with bumped dependencies for PHP (8.0) and Symfony (6).

**Comment by nitesh624** [comment] 2023-07-31 04:23
Thanks @tvdijen for the quick update. This will be  great and we can test and give feedback on new 2.1 release  after we will use it in our application.

**Comment by tvdijen** [comment] 2023-07-31 12:34
You can try the `simplesamlphp-2.1` release branch. If no issues show up in the next days I'm tagging a release

**Comment by nitesh-voya** [comment] 2023-08-03 06:08
ok

**Comment by abielefeldt** [comment] 2023-08-09 17:05
Looks like Twig has been bumped to ^3.7 but the Drupal core-recommended package only allows 3.5 for Drupal 10.0 or 3.6 for Drupal 10.1. Drupal installations using core-recommended won't be able to install this library. https://github.com/drupal/core-recommended/blob/10.1.x/composer.json#L60

Any possibility to downgrade the Twig version constraint to ^3.5 or ^3.6? Looking at the commit where that was done it seems twig/intl-extra was also bumped to ^3.7 but that package doesn't explicitly require Twig ^3.7; any 3.x will do: https://github.com/twigphp/intl-extra/blob/v3.7.0/composer.json#L19

**Comment by tvdijen** [comment] 2023-08-09 18:43
It's done!

**Comment by abielefeldt** [comment] 2023-08-18 19:25
For Drupal at least, two testers have confirmed that the `simplesamlphp-2.1` branch works, so this should be ready for a full 2.1 stable release.

Comments 91 and 94 here https://www.drupal.org/project/simplesamlphp_auth/issues/3349278#comment-15192128

**Comment by tvdijen** [comment] 2023-08-18 19:31
Thank you @abielefeldt !  I have two open issues before I can tag v2.1.0, but I'm confident I can close those issues soon.

**Comment by hekumar2** [comment] 2023-09-06 06:00
Hello [tvdijen] Any update on by when will you be able to tag2.1.0 ?

**Comment by tvdijen** [comment] 2023-09-06 07:36
I'm waiting for the last two PRs to be reviewed and then after some santity checking I'm good to go.
Maybe a week or so.

**Comment by folsomke** [comment] 2023-09-12 20:59
Some of us who are testing simplesamlphp-2.1 for use with Drupal 10 have found that the lack of primary keys for two database tables created by SimpleSAMLphp is causing an error message to be generated by the Drupal site status report function.  It is recommended that Drupal website databases have their transaction isolation level set to READ-COMMITTED.  When Drupal detects tables without primary keys, it reports that READ-COMMITTED won't work correctly without all tables having primary keys. Because SimpleSAMLphp is using a different database connection, the transaction isolation level is not truly compromised, but the status error could be confusing for website maintainers.

I was able to eliminate this error by changing two UNIQUE keys to PRIMARY keys in the noted tables.  These are

Table: SimpleSAMLphp_saml_LogoutStore
Key fields: _authSource + _nameId + _sessionIndex

Table: SimpleSAMLphp_tableVersion
Key field: _name

None of the key fields allow for NULL values, so this change should not affect operation, and my testing shows this is the case.

Would you be able to implement this change to the SimpleSAMLphp table keys for the 2.1 release?  Thanks.

**Comment by tvdijen** [comment] 2023-09-13 08:19
A pull request is much appreciated @folsomke !

**Comment by hekumar2** [comment] 2023-09-21 03:02
@tvdijen  @folsomke Can you please let us know what is the latest update ? When will you be able to create tag v2.1.0 ?

**Comment by tvdijen** [comment] 2023-09-21 07:02
> I'm waiting for the last two PRs to be reviewed and then after some santity checking I'm good to go. Maybe a week or so.

Nothing changed. It's done when it's done

**Comment by tvdijen** [comment] 2023-10-18 18:49
2.1.0-rc1 is available now that can be used instead of the tag requested. The final release will come shortly if no issues come to light in the next few weeks

**Closed by tvdijen** 2023-10-18 18:49 UTC

**Comment by hekumar2** [comment] 2023-10-19 03:25
Thanks @tvdijen  for the update.
