### ISSUE TITLE
Problem with port in method \SimpleSaml\Utils\HTTP::checkURLAllowed

### ISSUE THREAD

**Issue by andres-blanco** [simplesamlphp/simplesamlphp#337] opened 2016-02-29 18:53 UTC
Hey, I'am running an SP on http://localhost:4003. When I try to logout I get an exception that looks like this:

```
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
0 /var/local/huarpe-core/vendor/simplesamlphp/simplesamlphp/www/module.php:170 (N/A)
Caused by: SimpleSAML_Error_Exception: URL not allowed: http://localhost:4003/
Backtrace:
2 /var/local/huarpe-core/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php:332 (SimpleSAML\Utils\HTTP::checkURLAllowed)
1 /var/local/huarpe-core/vendor/simplesamlphp/simplesamlphp/modules/core/www/as_logout.php:18 (require)
0 /var/local/huarpe-core/vendor/simplesamlphp/simplesamlphp/www/module.php:127 (N/A)
```
After looking through the code we found that the method ``` \SimpleSaml\Utils\HTTP::getSelfHost``` is not returning the port, even tough in the function docs says this: ```* @return string The current host (with non-default ports included).```

Is this a bug?

**Comment by jaimeperez** [comment] 2016-03-01 11:03
Hola @andresote!

What value do you have in your `baseurlpath` configuration option? (`config/config.php`)

Also, can you verify the environment of your PHP script? Add a call to `error_log()` and monitor your apache error log to see what value does SimpleSAMLphp get from the environment, something like:

```php
private static function getServerPort()
    {
        $port = (isset($_SERVER['SERVER_PORT'])) ? $_SERVER['SERVER_PORT'] : '80';

        error_log("the port is: ".$port);

        if (self::getServerHTTPS()) {
            if ($port !== '443') {
                return ':'.$port;
            }
        } else {
            if ($port !== '80') {
                return ':'.$port;
            }
        }
        return '';
    }
```

**Comment by andresote** [comment] 2016-03-01 15:24
Hola @jaimeperez !

In the ```baseurlpath``` I have the default value: ```simplesaml/```.

The log in the ```getServerPort``` method returns: ```string(4) "4003"```

I think the problem is in the ```getSelfHost``` method:
```
    public static function getSelfHost()
    {
        $url = self::getBaseURL();

        $start = strpos($url, '://') + 3;
        // HERE. Why is the character ':' in the second parameter of strcspn?
        $length = strcspn($url, '/:', $start);

        return substr($url, $start, $length);
    }
```

For what it's worth, if in ```config.php``` I add the value: 
```'trusted.url.domains' => array('localhost:4003'),```
everything works correctly.

Saludos!

**Comment by thijskh** [comment] 2016-03-01 17:26
Looking in the history it seems getSelfHost() has never returned the port number with it. See 6351efb2456263f9811ca2ffad63a99cd9d72df1 when it was introduced: already there the port number is stripped.

Some code, e.g. https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Metadata/MetaDataStorageHandler.php#L209, does seem to assume a port number can be returned by getSelfHost, but apparently wants it without.

The docblock saying it does return port number was only added recently.

If some code wants it with, and some without port number, I think it makes sense to have just two functions that each do a predictable thing and not be stripping things off later. Of course, the new behaviour and that of checkURLAllowed could use some unittests to confirm their behaviour in different circumstances.

**Comment by jaimeperez** [comment] 2016-03-03 11:02
Andrés, please tell us if the latest code in master fixes the issue so that we can close it. Thanks!

**Comment by andres-blanco** [comment] 2016-03-03 17:57
Everything works fine now.

Cheers!

**Closed** 2016-03-03 18:50 UTC
Labels: bug, needsinfo

**Comment by Mathi05** [comment] 2018-03-16 10:39
Hi @jaimeperez ,

I am still facing this issue in latest build. I have my custom application which is developed on Codeigniter framework and runs in Google App Engine(http://localhost:8080/).

In login function, i am calling idp  which is working fine but after login, it throws an error like 

**SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
1 www/_include.php:45 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: SimpleSAML_Error_Exception: URL not allowed: http://localhost:8080/login
Backtrace:
2 lib/SimpleSAML/Utils/HTTP.php:383 (SimpleSAML\Utils\HTTP::checkURLAllowed)
1 modules/saml/www/sp/saml2-acs.php:116 (require)
0 www/module.php:135 (N/A)**

'baseurlpath' => 'http://localhost/POC/SAML-NEW/simplesamlphp/www/',

My Login function:
`public function login($msg = NULL) {
		require_once('/var/www/html/POC/SAML-NEW/simplesamlphp/lib/_autoload.php');
               $as = new SimpleSAML_Auth_Simple('myauthinstance');
               $as->requireAuth();
               $attributes = $as->getAttributes();
               print_r($attributes);
		exit;
      
    }`
  but if I directly log-in to myauthinstance it is working perfectly.

Can you help me out with this?
