### ISSUE TITLE
Loading a URL for the FederationMetadata

### ISSUE THREAD

**Issue by murraycollingwood** [simplesamlphp/simplesamlphp#1492] opened 2021-07-30 13:36 UTC
I'm using SSP as a Service Provider, and it's been working very well.

Currently our clients that are using our application have to upload new Token Signing Certificates from their ADFS / Azure systems every two years, as the certificates expire every two years.

These clients commonly provide us with a URL that will download a copy of their FederationMetadata thinking this will solve the problem, unfortunately we don't seem to have anywhere we can load this URL.  They still have to manually load a copy of the new certificate in order to get things working.   

Apparently, I'm told, other software that operates as Service Providers enter this URL into their systems and somehow the Service Provider is able to automatically access and load an updated copy of the certificate. This means that every two years when the certificate expires the ServiceProvider automatically uses the URL to download the FederationMetadata and update the certificate without any manual intervention.  Are we able to do this with SSP please?

**Comment by tvdijen** [comment] 2021-07-30 14:07
Hey @murraycollingwood ,

There's two options here;
1. You let your clients send you new metadata containing both the old and new certificate in advance.. You still have to take care of importing & converting it manually, but you would have like a grace period.  ADFS allows them to configure a grace-period where, once it starts, ADFS will automatically generate new certificates and publish it its their metadata.
2. You could use the metarefresh-module to automatically download the metadata xml from your peers.  I don't know if you have specific authproc-filters in place, but I believe it should even be possible to have their XML, and a record in `metadata/saml2-idp-remote.php` on the side with your IDP-specific authproc-filters.. (*)

(*)  I would have to check if this really is the case, because I don't think I've ever used it this way

**Comment by murraycollingwood** [comment] 2021-07-31 00:15
Hi @tvdijen (Tim)

I had no idea there was a MetaRefresh module or what it was for - sorry, it is probably documented in an area I didn't read.
I found some instructions in the MetaRefresh module.
```
[root@simplesamlphp] cd /var/simplesamlphp
[root@simplesamlphp simplesamlphp] touch modules/cron/enable
[root@simplesamlphp simplesamlphp] cp modules/cron/config-templates/*.php config/
[root@simplesamlphp simplesamlphp] touch modules/metarefresh/enable
[root@simplesamlphp simplesamlphp] cp modules/metarefresh/config-templates/*.php config/
```
I'm a little confused however. It looks as though these changes would be made in the 'vendor' directory.  That's not an area where I normally make changes, so I'm wondering is there an alternate location for the enable and configuration options?

**Comment by tvdijen** [comment] 2021-07-31 10:21
When you use `composer install` to install any of our modules, they should end up in the `modules/` directory instead of in the `vendor/` directory

**Comment by tvdijen** [comment] 2021-07-31 10:40
Ah, I see we have a problem.. This module is for some reason not installed in the modules-directory... I'll try and solve that

**Comment by tvdijen** [comment] 2021-07-31 11:29
It appears to be related to composer.. I have a fix pending for it, but if you stick to metarefresh 0.9.x it should work

**Comment by tvdijen** [comment] 2021-07-31 19:16
@murraycollingwood Would you mind trying to run `composer self-update` and try to install the metarefresh-module again?  I was able to reproduce this earlier today, but not anymore, so I'm a bit confused :/

**Comment by murraycollingwood** [comment] 2021-08-01 00:37
I ran the composer self-update:
```
kohekohe:trunk murraycollingwood$ composer self-update
Upgrading to version 2.1.5 (stable channel).
   
Use composer self-update --rollback to return to version 2.1.3
```

Then I tried updating simplesamlphp, and then later the specific metarefresh module with the following results:
```
kohekohe:trunk murraycollingwood$ composer install simplesamlphp/simplesamlphp-module-metarefresh
Invalid argument simplesamlphp/simplesamlphp-module-metarefresh. Use "composer require simplesamlphp/simplesamlphp-module-metarefresh" instead to add packages to your composer.json.
```

With require:
```
kohekohe:trunk murraycollingwood$ composer require simplesamlphp/simplesamlphp-module-metarefresh
Using version ^1.0 for simplesamlphp/simplesamlphp-module-metarefresh
./composer.json has been updated
Running composer update simplesamlphp/simplesamlphp-module-metarefresh
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - simplesamlphp/simplesamlphp is locked to version v1.19.1 and an update of this package was not requested.
    - simplesamlphp/simplesamlphp v1.19.1 requires simplesamlphp/simplesamlphp-module-metarefresh ^0.9 -> found simplesamlphp/simplesamlphp-module-metarefresh[v0.9.0, ..., v0.9.6] but it conflicts with your root composer.json require (^1.0).
  Problem 2
    - simplesamlphp/simplesamlphp v1.19.1 requires simplesamlphp/simplesamlphp-module-metarefresh ^0.9 -> found simplesamlphp/simplesamlphp-module-metarefresh[v0.9.0, ..., v0.9.6] but it conflicts with your root composer.json require (^1.0).
    - simplesamlphp/simplesamlphp-module-metarefresh v1.0.1 requires php >=7.4 || ^8.0 -> your php version (7.3.27) does not satisfy that requirement.
    - simplesamlphp/simplesamlphp-module-metarefresh v1.0.0 requires simplesamlphp/composer-module-installer ~1.1 -> satisfiable by simplesamlphp/composer-module-installer[v1.1.8].
    - simplesamlphp/composer-module-installer v1.1.8 requires simplesamlphp/simplesamlphp * -> satisfiable by simplesamlphp/simplesamlphp[v1.19.1].
    - Root composer.json requires simplesamlphp/simplesamlphp-module-metarefresh ^1.0 -> satisfiable by simplesamlphp/simplesamlphp-module-metarefresh[v1.0.0, v1.0.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```
I tried adding a specific version for the metarefresh to my composer.json file:
```
       "simplesamlphp/simplesamlphp-module-metarefresh": "^0.9",
       "simplesamlphp/simplesamlphp": ">=1.19",
```

This had the same result above.

**Comment by tvdijen** [comment] 2021-08-01 20:09
Ah, but wait... You're using 1.19, so the metarefresh-module is part of the package.. You don't have to install it manually!

**Comment by murraycollingwood** [comment] 2021-08-02 00:03
@tvdijen Hi Tim 

We are making progress.  

In config.php I now have:
```
    'module.enable' => array(
        'metarefresh' => true,
        'cron' => true
    ),
```

I've copied config-metarefresh.php to my config folder.
I've copied module_cron.php to my config folder.

Keeping in mind that all of my SAML data (the stuff normally stored in these configuration files) is actually all stored in a database table.  I can generate the config-metarefresh config array, a little like this:
```
// Locate all the schools with a Federation URL entry
$fedEntries = SamlQuery::create()
                    ->filterByKey(SamlQuery::KEY_FED_URL)
                    ->find();

foreach ($fedEntries as $fedEntry) {
    $school = SchoolQuery::create()->findPk($fedEntry->getSchoolid());

    // We must have an existing certificate entry
    $certEntry = SamlQuery::create()
                        ->filterBySchoolid($school->getId())
                        ->filterByKey(SamlQuery::KEY_CERTIFICATE)
                        ->findOne();
    if (!$certEntry)
        continue;

    // Add this entry
    $schoolKey = "school" . $school->getId();
    $set = array(
        'cron' => ['daily'],
        'sources' => [ [ 
            'src' => $fedEntry->getPlaintext(),
            'certificates' => [ $certEntry->getFilename() ] 
            ] ]
    );

    $config['sets'][$schoolKey] = $set;
}
```

What I'm confused about is how to deal with the new values to be stored and the new certificate to be used.
It looks as though the only option is to save them to a flat file.  I want them passed to a function I define so I can update the entries in the database table.

Is there a hook for this?

With my limited SAML experience my main issue has always been the update to the certificate, so as a very quick work-around, if we could simply replace the current certificate with the new one (using the same filename) that would work for me.

**Comment by tvdijen** [comment] 2021-08-02 07:39
I don't think there's an option for that, so you may have to use your work-around there...
Unless perhaps @dnmvisser has an idea? You're using this module, right?

**Comment by murraycollingwood** [comment] 2021-08-02 10:42
@tvdijen Hi Tim

I'm thinking that I will get the metarefresh module to store the metadata into a folder, and then schedule a second job (of my own) to then process the data from the folder into the database table.  Hopefully that should work.

**Comment by murraycollingwood** [comment] 2021-08-05 01:40
@tvdijen Hi Tim

The documentation isn't clear in a couple of areas.
```
cd modules/metarefresh/bin
./metarefresh.php -s http://metadata.aai.switch.ch/metadata.aaitest.xml
```
This doesn't work for me.  Firstly, I don't allow PHP files to be executed from the command line, and second,if I run this using the php command the "-s" simply outputs the contents of the metarefresh.php file.  That is, "-s" is an option in the php command:
```
  -s               Output HTML syntax highlighted source.
```
When I run this command without the "-s" nothing happens.  No output, no (obvious) errors.  It certainly doesn't appear to load the config-metarefresh.php file as I have an error_log() in there and it hasn't been executed.

For security reasons the cron on my servers is restricted to 'root' access only. Users (like the web server user) can't access a cron.
So I was going to simply add the command to my own cron job.  However I can't find the command.  Again, nothing in the documentation tells me what should be run.

Hope you can help.

My config-metarefresh.php looks like the following (main part only included):
```
$config = [ 'sets' => [] ];

$fedEntries = SamlQuery::create()
                    ->filterByKey(SamlQuery::KEY_FED_URL)
                    ->find();

foreach ($fedEntries as $fedEntry) {
    $school = SchoolQuery::create()->findPk($fedEntry->getSchoolid());

    // We must have an existing certificate entry
    $certEntry = SamlQuery::create()
                        ->filterBySchoolid($school->getId())
                        ->filterByKey(SamlQuery::KEY_CERTIFICATE)
                        ->findOne();
    if (!$certEntry)
        continue;
    // We only want to use the new format certificates
    $prefix = substr($certEntry->getFilename(), 0, 11);
    if ($prefix != "../../cert/")
        continue; // Drop off some relative directories
    $certFileName = substr($certEntry->getFilename(), 11);

    // We need to store this stuff and process it with another cron job
    $outputDir = "metadata/metarefresh-$schoolKey/";
    $actual = "conf-simplesaml/" . $outputDir;  
    if (!directoryExists($actual)) { // Ensure my outputDir exists
        mkdir($actual, 0777, true);
    }

    // Add this entry
    $schoolKey = "school" . $school->getId();
    $set = array(
        'cron' => ['daily'],
        'sources' => [ [ 
            'src' => $fedEntry->getPlaintext(),
            'certificates' => [ $certFileName ] 
            ] ],
        'outputDir'    => $outputDir,
        'outputFormat' => 'flatfile'
    );

    $config['sets'][$schoolKey] = $set;
}

// Show me what it looks like
error_log("metarefresh config array = " . print_r($config, true));
```

**Comment by tvdijen** [comment] 2021-08-05 07:59
Hi @murraycollingwood !   I think the command should be without the `-s`.. I'll remove that from the docs.
As for cron, that really depends on your OS, but on most linux-based systems you would do `crontab -e` to edit a user's crontab.

If you're concerned with security, you _really_ shouldn't be running any crons as root..  It allows an attacker to put some code in the `bin/metarefresh.php` and basically gain root-access this way.

**Comment by tvdijen** [comment] 2021-08-22 15:16
@murraycollingwood Have you figured something out? Can I close this issue?

**Comment by thijskh** [comment] 2021-08-22 15:31
BTW metarefresh is not usually called from that commandline but via SSP’s cron module. That module just requires a curl call to the cron module’s daily/hourly endpoint. This can be done as root as no actual
code is executed then as root. This is fully documented in the cron module docs.

**Comment by tvdijen** [comment] 2021-08-22 16:01
Any auditor will have our heads for the docs as they are.. cron-jobs should never be run under the webserver-user.
If you split webserver and php by using php-fpm under a different user, it should be fine.. We should really update the docs

**Comment by thijskh** [comment] 2021-08-22 16:03
This is a tradeoff between maximum security and ease of setup in (esp.) limited hosting environments… I guess it’s up to the admin to interpret our docs.

**Comment by tvdijen** [comment] 2021-08-22 16:09
I do not disagree, but we should at least try and propagate safe use..

**Comment by murraycollingwood** [comment] 2021-09-17 00:19
[bump] 
I'm still not sure where the script file should be run from.  
Based on the code all being loaded into the 'vendor' directory and the configuration local to my application, I'm assuming I should be somewhere relative to the config-metarefresh.php file, but where?

**Comment by thijskh** [comment] 2021-09-17 07:07
You put `config-metarefresh.php` in SimpleSAMLphp's global `config/` dir (as is in the docs).

You can run `metarefresh.php` from anywhere you want.

```
thijs:~/simplesamlphp$ ls -l config/config-metarefresh.php 
-rw-r--r-- 1 thijs nogroup 1910 Aug 23 10:08 config/config-metarefresh.php
thijs:~/simplesamlphp$ modules/metarefresh/bin/metarefresh.php -s https://metadata.surfconext.nl/idp-metadata.xml|head -4
/* The following data should be added to metadata/saml20-idp-remote.php. */

/* The following metadata was generated from https://metadata.surfconext.nl/idp-metadata.xml on 2021-09-17T07:05:02Z. */
$metadata['https://engine.surfconext.nl/authentication/idp/metadata'] = array (
```

**Comment by murraycollingwood** [comment] 2021-09-17 08:27
Still not working but I found more information:
```
root@focus2:/home/sobs# php -f vendor/simplesamlphp/simplesamlphp/modules/metarefresh/bin/metarefresh.php -- -s https://metadata.surfconext.nl/idp-metadata.xml
root@focus2:/home/sobs# 
```
In the error log I found this:
```
[17-Sep-2021 18:01:28 Australia/Brisbane] PHP Fatal error:  Uncaught SimpleSAML\Error\CriticalConfigurationError: The configuration (config/config.php) is invalid: Missing configuration file in /home/so
bs/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Error/CriticalConfigurationError.php:84
Stack trace:
#0 /home/sobs/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Configuration.php(352): SimpleSAML\Error\CriticalConfigurationError::fromException(Object(SimpleSAML\Error\ConfigurationError))
#1 /home/sobs/vendor/simplesamlphp/simplesamlphp/modules/metarefresh/lib/MetaLoader.php(327): SimpleSAML\Configuration::getInstance()
#2 /home/sobs/vendor/simplesamlphp/simplesamlphp/modules/metarefresh/lib/MetaLoader.php(108): SimpleSAML\Module\metarefresh\MetaLoader->createContext(Array)
#3 /home/sobs/vendor/simplesamlphp/simplesamlphp/modules/metarefresh/bin/metarefresh.php(149): SimpleSAML\Module\metarefresh\MetaLoader->loadSource(Array)
#4 {main}
  thrown in /home/sobs/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Error/CriticalConfigurationError.php on line 84
```

This seems to imply you can't just run this from anywhere.
My config isn't even in this directory, mine are located in "conf-simplesaml/config.php" and "conf-simplesaml/config-metarefesh.php"

So how do I specify that location to this script?

For the web based access there is an environment variable set in my Apache configuration:
```
        SetEnv          SIMPLESAMLPHP_CONFIG_DIR /home/sobs/build/conf-simplesaml
        Alias           /simplesaml     /home/sobs/vendor/simplesamlphp/simplesamlphp/www
```

So, can I set an Environment variable like this for the script... (checking now)... HURRAY!

I am now running the metarefresh with:
```
export SIMPLESAMLPHP_CONFIG_DIR="/home/sobs/build/conf-simplesaml"
php -f vendor/simplesamlphp/simplesamlphp/modules/metarefresh/bin/metarefresh.php -- -s https://metadata.surfconext.nl/idp-metadata.xml
```

This is now giving me a configuration array.
I think we can close this issue now - I should be able to manage the rest myself.

Thanks again for everybody's help.

**Comment by tvdijen** [comment] 2021-09-17 08:33
Ah, yes I knew about the environment variable, but I wasn't aware you had your setup like that..
We should probably add this to the docs for the  metarefresh-module (and any other module that has bin-scripts like statistics, cron)

**Comment by thijskh** [comment] 2021-09-17 10:06
If you change the config dir to something nonstandard with an environment variable you need set this environment variable in any environment you wish to run SSP code. There's nothing metarefresh specific about this?

**Comment by tvdijen** [comment] 2021-09-17 10:09
Yes, we have documented this for Apache, but I don't think we mention anywhere how this works for bin-scripts..
I agree it's not specific to metarefresh, but generic for any module that has bin-scripts.

**Comment by tvdijen** [comment] 2022-09-16 20:06
I've added a note on the environment variable in https://github.com/simplesamlphp/simplesamlphp-module-metarefresh/commit/7f66b515b8a2c4781904e972437812441ef9d296

**Closed by tvdijen** 2022-09-16 20:06 UTC
