### ISSUE TITLE
admin.protectindexpage has no effect on new ui

### ISSUE THREAD

**Issue by greenacorn-michael** [simplesamlphp/simplesamlphp#1060] opened 2019-03-08 05:29 UTC
When enabling the new UI in 1.17.1 the web interface is open and accessible, even if protected.

1. Update to 1.17.1
2. Add ```$config['usenewui'] = true;``` to your config.php file
3. Set ```admin.protectindexpage``` to ```true```
4. Open the web interface

**Expected behavior**
User is prompted for a password

**Comment by jaimeperez** [comment] 2019-03-08 09:29
Hi @greenacorn-michael!

I'm a bit confused here. I've been testing this myself, and you will always get prompted for a password, both if you are accessing the regular user interface or if you are trying to enter the new admin interface. The only thing that I can imagine is that you have more than one authentication source defined, and then you are first asked to choose which one to use to log in.

All of this is normal, intentional and by design. In the new interface, there's a clear separation between admin interface and end-user interface. The admin interface can be disabled by simply disabling the admin module. The user interface is the bare minimum (authentication and management of consent or other end-user-related information), so there's nothing to protect there actually.

Is this the case that you are observing?

**Comment by greenacorn-michael** [comment] 2019-03-08 12:25
Yes, I have two authentication sources. A user can log in to one via the web interface and then see all their own attributes, whereas I'd rather this only be accessible via my website. Not a big deal for me, but some other sites could have admin-only type data about their users in the attributes, unless I've misunderstood something.

So if I removed one of my authentication sources you're saying a regular user would only see a password prompt? Is that the admin password?

FWIW I did add ```$config['module.enable']['admin'] = FALSE;``` to my config.php file but was still able to access the admin pages via their direct URLs.

**Comment by tvdijen** [comment] 2019-03-14 20:15
Hi @greenacorn-michael !

I'm pretty sure you're using the 'old' `module.php/core/frontpage_config.php` endpoints instead of the new `/module.php/admin/` ones... This is exactly the reason why we're moving this functionality to a separate module in the new UI. Right now both old/new co-exist, but the old style will be removed in a 2.0 version of SimpleSAMLphp.  The user interfaces should be public nonetheless

**Closed by tvdijen** 2019-03-14 20:15 UTC
Labels: needsinfo

**Comment by jaimeperez** [comment] 2019-03-15 09:39
> Yes, I have two authentication sources. A user can log in to one via the web interface and then see all their own attributes, whereas I'd rather this only be accessible via my website. Not a big deal for me, but some other sites could have admin-only type data about their users in the attributes, unless I've misunderstood something.

This is definitely not standard practice, so if you want to hide attributes from the users, you'll need to manage that on your own. In any case, I wouldn't recommend you to do that.

Regarding `admin.protectindexpage`, when you set it to `true` in the old interface, you are not protecting with an admin password the page where users can authenticate. That page is still available and working if you just go there. Considering this, this would be _security by obscurity_, which is considered bad practice in terms of security.

> So if I removed one of my authentication sources you're saying a regular user would only see a password prompt?

Yes. Username and password, actually.

> Is that the admin password?

No, they will be able to login with their username and password. What you see when you access the root of your SimpleSAMLphp installation is the (end) user interface, which is intended for users to see their information and manage anything that they can manage (like consent, for example).
