### ISSUE TITLE
session_create_id causes SIGSEGV

### ISSUE THREAD

**Issue by iluuu1994** [simplesamlphp/simplesamlphp#1158] opened 2019-07-05 14:37 UTC
**Describe the bug**

Since we have updated to SimpleSaml 1.17 we get daily SIGSEGV of PHP-FPM due to the new call to `session_create_id()`:

https://github.com/simplesamlphp/simplesamlphp/blob/f5989a7223d995f5275159520f22215eacf5b6fa/lib/SimpleSAML/SessionHandlerPHP.php#L152

**/var/log/kern.log**

```log
Jul  5 16:00:03 servername kernel: [265630.815422] traps: php-fpm7.3[21032] general protection ip:5580a3494efd sp:7fff8cff8498 error:0
Jul  5 16:00:03 servername kernel: [265630.815428]  in php-fpm7.3[5580a3231000+3ee000]
```

**/var/log/php7.3-fpm.log**

```log
[05-Jul-2019 16:24:44] WARNING: [pool www] child 21558 exited on signal 11 (SIGSEGV) after 0.454303 seconds from start
[05-Jul-2019 16:24:44] NOTICE: [pool www] child 21561 started
```

This is the PHP version we use:

```log
PHP 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7 (cli) (built: May 31 2019 11:27:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7, Copyright (c) 1999-2018, by Zend Technologies
```

**To Reproduce**

Unfortunately, we could not recognize any patterns on how to reproduce the issue. It seems to happen randomly.

Obviously this is not your issue to solve but I'm posting this here for two reason:

* Have you encountered this issue before?
* Could SimpleSaml add an option to use `bin2hex(openssl_random_pseudo_bytes(16))` instead?

Thank you!

**Comment by tvdijen** [comment] 2019-07-05 20:17
Ha, that was the same behaviour I was seeing but I didn't look into it any further yet due to time restrictions!
I'm not sure what they mean exactly, but I've seen it happen with different IP/SP's.. I think IP is 'instruction pointer':

``messages-20190630:Jun 26 10:59:01 webapp-1 kernel: traps: php-fpm[7336] general protection ip:556723c8db12 sp:7fff45524e88 error:0 in php-fpm[5567239d6000+460000]``
``messages-20190630:Jun 26 11:01:02 webapp-1 kernel: traps: php-fpm[7430] general protection ip:56140cf20b12 sp:7fffd68879c8 error:0 in php-fpm[56140cc69000+460000]``

**Comment by iluuu1994** [comment] 2019-07-05 20:42
I'm honestly relieved to hear that we're not the only ones with this issue. Do you think this is critical enough to switch to the old session is generation until this issue is fixed?

> have you reported this at PHP already?

Not yet. I was trying to get a core dump to get some debugging information but didn't succeed yet. I'll try tomorrow and I'll create a bug report then.

Thank you @tvdijen for your response!

**Comment by tvdijen** [comment] 2019-07-05 20:48
I'd like to have a look at the core dump and see how they respond to the bug-report before we start jumping hoops, but it's definitely an option to disable it until a solution is in place.

**Comment by iluuu1994** [comment] 2019-07-05 20:52
@tvdijen Fair enough! I can send a PR for the option tomorrow.

**Comment by tvdijen** [comment] 2019-07-05 21:01
Thanks for the offer, but I think I prefer a `&& version_compare(phpversion(), '7.3', '<')` added to [this](https://github.com/simplesamlphp/simplesamlphp/blob/f5989a7223d995f5275159520f22215eacf5b6fa/lib/SimpleSAML/SessionHandlerPHP.php#L145) line.. If we add this to 1.17 it would buy us some time to get to a more permanent solution. No need for a PR for such a one-liner ;)

**Comment by iluuu1994** [comment] 2019-07-05 21:03
Great! Thanks for your help!

**Comment by tvdijen** [comment] 2019-07-09 06:55
Can either of you confirm that the patch by @mrtronje gets rid of the SIGSEGV's?

**Comment by iluuu1994** [comment] 2019-07-09 07:30
@tvdijen Yes, we have been using it in production for a few days and have non more SIGSEVs.

**Comment by tvdijen** [comment] 2019-07-09 08:04
@iluuu1994 Did you manage to get some debug logging and to report a bug @php?

**Comment by jaimeperez** [comment] 2019-07-09 08:40
I have mixed feelings about this. On the one hand, it's really bad that we're getting SIGSEGVs with PHP 7.3 by simply using the software. On the other hand, that's clearly a bug in PHP that should be solved. The issue I see with the one-liner is that it would downgrade session ID generation for everyone using PHP 7.3, no matter if the bug is fixed or not. So if PHP 7.3.8 is released tomorrow fixing this issue, people running SSP 1.17.3 would still use non-collision-resistant session IDs unless we release SSP 1.17.4 reverting the one-liner and they install it.

I've been looking for a bug report, but didn't see anything. We should definitely report this to PHP and get it fixed there. Whether we should apply the one-liner as a temporary workaround, I honestly don't know...

@thijskh do you have any comments on this?

**Comment by iluuu1994** [comment] 2019-07-09 08:50
@tvdijen Unfortunately not. We haven't had a lot of time lately to look into it. I'll have to do it in my free time.

@jaimeperez

> would still use non-collision-resistant session IDs unless we release SSP 1.17.4 reverting the one-liner and they install it.

Another simple version check will do it once it's fixed. A slightly less optimal session id generation is preferable a crashing application.

**Comment by thijskh** [comment] 2019-07-09 09:28
I agree with @jaimeperez that I'd be uneasy to disable this for all future PHP versions. We'd definitely need some way to come back to this issue later to see if it's still relevant. Maybe we can apply the workaround only in 1.17.3 and keep this issue open for 1.18. And indeed obviously file an issue with PHP itself.

**Comment by iluuu1994** [comment] 2019-07-09 09:33
Why not just:

```php
if (
    function_exists('session_create_id')
    && (
        version_compare(phpversion(), '7.3', '<')
        || version_compare(phpversion(), '7.3.future_patched_version', '>=')
    )
) {
```

After a reasonable amount of time this could be removed.

**Comment by thijskh** [comment] 2019-07-09 09:39
That is useful in the future but not something we can do now since we don't know the value of future_patched_version yet.

**Comment by jaimeperez** [comment] 2019-07-09 09:51
I agree that having PHP crash is much, much worse than anything else.

What about applying this one-liner fix, releasing 1.17.3, then reverting the fix? We keep the issue open, and before releasing next version, we check if there is a fix in PHP already. If not, apply the same patch. If it is resolved, then apply your suggested check to avoid only affected versions, and then commit that to master as well.

Does that sound reasonable?

**Comment by iluuu1994** [comment] 2019-07-09 10:03
Sounds good 🙂

**Comment by thijskh** [comment] 2019-07-09 11:14
Let's go for it

**Comment by thijskh** [comment] 2019-07-09 11:46
I have applied the temporary workaround on the 1.17 branch now.

**Comment by iluuu1994** [comment] 2019-07-09 12:26
Thanks guys!

**Comment by tymees** [comment] 2019-07-10 07:29
Hey all,

We've encountered this SIGSEGV on our servers too, running on PHP 7.3 as well. However, we only encountered this with SSP 1.17.2, downgrading to 1.17.1 fixed this issue for us.

I don't see any changes that directly relate to the session generation when looking at the commit comparisons between these versions. It could be that I'm overlooking something, I don't really know this codebase of course.

Does anyone know why this downgrade solved it for us? (Just to be sure that there isn't a different issue at play here and I can upgrade safely)

**Comment by tvdijen** [comment] 2019-07-10 08:03
The only significant change between those versions is that we've started using Webmozart-assertions on the saml2-library.. What happens if you run v1.17.2 and downgrade `simplesaml/saml2` to v3.3.9?

**Comment by jaimeperez** [comment] 2019-07-10 10:52
We have 1.17.3 in place now with the fix for this 😄

**Comment by tymees** [comment] 2019-07-10 11:07
> The only significant change between those versions is that we've started using Webmozart-assertions on the saml2-library.. What happens if you run v1.17.2 and downgrade `simplesaml/saml2` to v3.3.8?

This didn't fix the errors sadly. However, 1.17.3 does seem to fix it for now. 

That still doesn't explain why 1.17.1 seems to work for us, but I don't think it's worth it to keep digging for an answer.

**Comment by txigreman** [comment] 2019-07-29 18:07
Hi guys,

The issue is not related exclusively to PHP 7.3, I'm getting the SIGSEGV error en 7.2. I changed the comparision of the workaround from 7.3 to 7.2 and now its working. It was previously failing with both PHP 7.2.19 and 7.2.20.

**Comment by iluuu1994** [comment] 2019-07-29 18:17
We never tried this on 7.2. We were stuck on PHP 7.0 and thus also on an older version of SimpleSaml that didn't use `session_create_id`. Thanks for letting us know.

If anybody can get a stack trace please post it in the comments of the [bug report](https://bugs.php.net/bug.php?id=78295).

**Comment by jaimeperez** [comment] 2019-09-16 11:24
Hi guys,

I'm considering introducing a regression deliberately. We are on the verge of release 1.18 (at least the first release candidate), and I would like to get rid of this temporary fix if possible. I've been trying to reproduce this locally in the command line with the two versions of PHP that are reportedly causing crashes (7.2 and 7.3). Essentially, I'm creating millions of session IDs with `session_create_id()` in a loop. So far, I've been unable to reproduce it.

@iluuu1994, @txigreman, @tymees would you be willing to give 1.18-rc1 a try and tell us if you still get those crashes or not?

**Comment by iluuu1994** [comment] 2019-09-16 11:27
> Essentially, I'm creating millions of session IDs with session_create_id() in a loop

I've tried that back then too but couldn't reproduce it this way. I highly doubt the issue is gone since there was no activity in the PHP bug report...

**Comment by tvdijen** [comment] 2019-09-16 12:40
I just deployed current `master` without the fix on a fully updated PHP 7.3 install.. Let's see what happens..

**Comment by txigreman** [comment] 2019-09-16 18:51
Sorry, but I can not test it because it only happens in the production server :/
For me the way to replicate the error was changing the value of the SimpleSAML cookie. I hope it works for you!

**Comment by tymees** [comment] 2019-09-18 13:05
I've deployed the latest master on our acceptation server, so far no issues...

I'll do some testing next week when I come back to work

**Comment by tvdijen** [comment] 2019-09-24 13:42
I found out how to create coredumps and it's actually quite easy:
https://ma.ttias.be/generate-php-core-dumps-segfaults-php-fpm/

I have enabled it on my 7.2 + 7.3 machine to add to the chance to catch one.. It would help if you guys could all do this, so we can get this fixed by PHP ASAP..

**Comment by iluuu1994** [comment] 2019-09-24 13:53
@tvdijen Yeah those are the same instructions we've followed but for some reason the core dump file was never generated. Hopefully you'll have more luck.

**Comment by tvdijen** [comment] 2019-12-24 20:52
I haven't been able to generate core dumps with the provided instruction either.. @tymees have you had any problems with more recent versions of SSP?

**Comment by tymees** [comment] 2019-12-25 11:01
Not that I know of no, error logs look clean too!

**Comment by thijskh** [comment] 2020-02-25 09:51
Given the feedback above I think it’s ok to close this now.

**Comment by jaimeperez** [comment] 2020-02-25 10:24
1.18 has been using the temporary patch we created as well, so the fact that we haven't had any more people observing segfaults doesn't mean the issue is gone, unfortunately 😞

**Comment by jaimeperez** [comment] 2020-02-25 14:43
My bad, Tim just corrected me that all the feedback we have now (confirming the issue is gone) was based on master, which didn't have the workaround in place, so I'm closing it back. Sorry for the noise!

**Closed by jaimeperez** 2020-02-25 14:43 UTC
Labels: medium
