### ISSUE TITLE
Class SimpleSAML\Session has no unserializer

### ISSUE THREAD

**Issue by DerMega** [simplesamlphp/simplesamlphp#1826] opened 2023-07-13 13:47 UTC
**Describe the bug**
I upgraded our dev Server to PHP 8.0.13
I then downloaded SSPHP 2.0.4 fitted the config php and metadatafiles and tested my system.
When I invoke SSPHP like in the following I get an error:
```
$ssFile = '/var/www/simplesamlphp/lib/_autoload.php';
if(file_exists($ssFile)) {
        require_once($ssFile);
        $as = new \SimpleSAML\Auth\Simple('default-sp');
        $as->requireAuth();
        $userName = $as->getAttributes()['username'][0];
}
```

```
Warning:  Class SimpleSAML\Session has no unserializer in /var/www/simplesamlphp/src/SimpleSAML/SessionHandlerPHP.php on line 248

Fatal error:  Uncaught Error: Typed property SimpleSAML\Session::$trackid must not be accessed before initialization in /var/www/simplesamlphp/src/SimpleSAML/Session.php:552
Stack trace:
#0 /var/www/simplesamlphp/src/SimpleSAML/Session.php(399): SimpleSAML\Session->getTrackID()
#1 /var/www/simplesamlphp/src/SimpleSAML/Session.php(281): SimpleSAML\Session::load(Object(SimpleSAML\Session))
#2 /var/www/simplesamlphp/src/SimpleSAML/Auth/Simple.php(52): SimpleSAML\Session::getSessionFromRequest()
```

**To Reproduce**
see bug description

**Expected behavior**
SimpleSamlPHP loads with no errors

**Screenshots or logs**
--

**Additional context**
--

**Comment by tvdijen** [comment] 2023-07-13 17:05
You get the error immediately, or after returning from the IDP?

**Comment by DerMega** [comment] 2023-07-14 05:37
Thats a good question.
I set the logs to file but in the logfolder there are no logfiles from ssphp.
How can I figure out when it happens?

**Comment by tvdijen** [comment] 2023-07-14 08:20
Well, for starters, get the logs to work :')  There must be some permissions-issue with the logs-directory. You can also use the SAML-tracer add-on for Firefox/Chrome to inspect the traffic.

**Comment by DerMega** [comment] 2023-07-14 11:29
I don´t know ... it refuses to log something.
I set the loggingdir to the following:
'loggingdir' => 'log/' 

The logginghandler loocks like this:
'logging.level' => SimpleSAML\Logger::DEBUG,
'logging.handler' => 'file',

Apache can write to the folder. I tested it.

**Comment by tvdijen** [comment] 2023-07-14 11:44
What platform are you running?

**Comment by DerMega** [comment] 2023-07-14 13:21
Its a RedHat Enterprise Linux 8 machine.
I tried 'errorlog' and 'syslog' but nothin in the Apache logs or the syslog either.

Linux is not my profession. That´s a big problem here ... :-/

**Comment by tvdijen** [comment] 2023-07-17 13:14
We can't really help you with support on your OS.. Something funny is going on there.

**Comment by DerMega** [comment] 2023-07-17 13:18
It is ... :D

I´m coming back when I have sorted it out. 
Thanks anyway :)

**Comment by tvdijen** [comment] 2023-09-05 23:19
Closing this.. I'm unable to reproduce this. Feel free to get back to us when you have some more details.

**Closed by tvdijen** 2023-09-05 23:19 UTC
