### ISSUE TITLE
Support symfony 7 package

### ISSUE THREAD

**Issue by apathak18** [simplesamlphp/simplesamlphp#2164] opened 2024-07-05 08:11 UTC
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Specifics of your environment**
1. Are you acting as SP/IdP/proxy? - SP
2. SimpleSAMLphp: What version are you using? - 2.2
3. PHP: What version are you using? 8.3
4. Platform: unix or Windows? unix
5. Webserver: Apache/Nginx/ISS? apache

**Describe the bug**
With latest release of SimpleSAMLphp application won't run on symfony 7

**To Reproduce**
Trying to Include this package with the existing application which running on symfony 7 version.

**Expected behavior**
Both both 6.4 and 7 version of symfony package so that this package would installed and compatible to use.
**Screenshots or logs**
If applicable, add screenshots and/or log files to help explain your problem.
<img width="1021" alt="Screenshot 2024-07-05 at 1 39 49 PM" src="https://github.com/simplesamlphp/simplesamlphp/assets/106175376/683db6eb-a7fa-424e-8407-f5a006621c53">

**Comment by tvdijen** [comment] 2024-07-05 09:18
Duplicate of https://github.com/simplesamlphp/simplesamlphp/issues/2122 and https://github.com/simplesamlphp/simplesamlphp/issues/2008

See you back in nov 2025 when Symfony 7 becomes LTS.

**Closed by tvdijen** 2024-07-05 09:18 UTC

**Comment by HenkPoley** [comment] 2024-09-06 08:31
Hi Tim,

Thank you so much for your hard work and all the great support you provide for this project. I completely understand your decision to wait until Symfony 7 becomes Long-Term Support (LTS) in November 2025.

However, I wanted to bring up a small point for consideration. The widely used Laravel 10, which will reach its end of security support by **February 4th, 2025**, depends on Symfony 6.4, just like this package. Its successor, Laravel 11, relies on Symfony 7.0, meaning that after February 2025, there’s a gap of about 9 to 10 months until November 2025 where users may face a tricky situation in terms of security.

Since this package is essential for authentication security, I thought it might be worth reconsidering the timeline, so those who upgrade to Laravel 11 can continue using this useful library without interruption.

Thanks again for all the awesome work you do!

**Comment by tvdijen** [comment] 2025-08-21 15:40
We have a `simplesamlphp-2.5` release-branch now that you can use. There are no tagged releases in that branch yet, but I can tag a beta or rc on request. A final 2.5.0 release will come as soon as Symfony tags 7.4 in november.
