### ISSUE TITLE
For saml2, should the prevAuth not track the stateId instead of the responseId?

### ISSUE THREAD

**Issue by sandermarechal** [simplesamlphp/simplesamlphp#648] opened 2017-06-28 15:06 UTC
I'm having a bit of a problem with my SAML2 integration. Our users are suffering an aweful lot of NOSTATE errors. I can reproduce this by going to my site, logging in, and hitting back. Here's what happens:

1) Go to my site, get redirected to IdP
2) Log in at IdP (POST). Get redirected to a response page (GET).
3) IdP does a POST-redirect to SimpleSamlPhp saml2-acs.php (i.e. show HTML with hidden form that auto-submits)
4) saml2-acs.php redirects back to my site

The problem happens when a user now hits the "back" button. He goes back to (3). The IdP now generates a new samlp:Response with a new ID, but the inResponseTo is the same. This response auto-submits to saml2-acs.php. Because $prevAuth only checks the response ID and not the response inResponseTo ID, the resend detecttion fails and SimpleSaml errors out with NOSTATE.

I changed saml2-acs.php to store the $response->getInResponseTo() ID in $prevAuth instead of the $response->getId() and now it works.

Is this a bug in SimpleSaml? Or is this a bug at my IdP? Is it correct that they generate a new response with a new ID for the same SamlRequest?

**Comment by jaimeperez** [comment] 2017-06-30 08:15
Hi @sandermarechal!

The check that we have in place (same response ID) must be there as it is mandated by the standard, which says that duplicate responses should be disregarded as a security protection.

We cannot actually track the `InResponseTo` field here as there could be valid use cases that could trigger such an scenario where we get different responses relative to the same state. Now, there is indeed a bug in the code:

1. The mechanism detecting duplicate responses fails, as the response ID is different.
2. The code goes on and tries to load the state referenced by `InResponseTo`.
3. At this point, if the state still exists but the _stage_ has changed, an exception is triggered in the second part of `SimpleSAML_Auth_State::loadState()`. Since we don't include a _emergency_ URL in the state identifier, the method just triggers the exception instead of redirecting to such URL.
4. Alternatively, if the state is gone, the first part of `SimpleSAML_Auth_State::loadState()` throws a `SimpleSAML_Error_NoState` exception.
4. The exception (whichever it is) isn't captured and the user sees the error.

This situation shouldn't happen. In this case, we should treat this case as an _unsolicited response_. The side effect to this, though, could be that the users end up in a completely different page, but at least they won't get an error.

I can't test this myself because when SSP acts as an IdP the response ID is the same when hitting the back button, so I can't reproduce your steps. In any case, I've created a patch that should fix your issue. Do you mind applying it and telling me if it works?

```patch
diff --git a/modules/saml/www/sp/saml2-acs.php b/modules/saml/www/sp/saml2-acs.php
index e98f60b..194e009 100644
--- a/modules/saml/www/sp/saml2-acs.php
+++ b/modules/saml/www/sp/saml2-acs.php
@@ -72,11 +72,20 @@ if ($prevAuth !== null && $prevAuth['id'] === $response->getId() && $prevAuth['i

 $idpMetadata = array();

+$state = null;
 $stateId = $response->getInResponseTo();
 if (!empty($stateId)) {
-    // this is a response to a request we sent earlier
-    $state = SimpleSAML_Auth_State::loadState($stateId, 'saml:sp:sso');
+    // this should be a response to a request we sent earlier
+    try {
+        $state = SimpleSAML_Auth_State::loadState($stateId, 'saml:sp:sso');
+    } catch (Exception $e) {
+        // something went wrong,
+        SimpleSAML_Logger::warning('Could not load state specified by InResponseTo: '.$e->getMessage().
+            ' Processing response as unsolicited.');
+    }
+}

+if ($state) {
     // check that the authentication source is correct
     assert('array_key_exists("saml:sp:AuthId", $state)');
     if ($state['saml:sp:AuthId'] !== $sourceId) {
```

**Comment by sandermarechal** [comment] 2017-07-04 08:15
I just tested it and it works! Thanks!

**Comment by jaimeperez** [comment] 2017-07-04 08:20
Awesome! I've merged the fix into master. I'll look into fixing this into 1.14.x too 👍

**Closed by jaimeperez** 2017-07-04 08:20 UTC
Labels: bug, needsinfo

**Comment by sandermarechal** [comment] 2017-07-04 13:16
Thanks, that would be great!
