### ISSUE TITLE
Helpful exception message lost when SAML2 metadata expired

### ISSUE THREAD

**Issue by leonstr** [simplesamlphp/simplesamlphp#183] opened 2015-03-27 14:29 UTC
If you have an SSp Service Provider with metadata for a SAML20 IdP in `metadata/saml20-idp-remote.php`, and this metadata has expired (i.e. the 'expire' value has been exceeded) then you get the message:

> SimpleSAML_Error_Exception: Could not find the metadata of an IdP with entity ID '...entity_id...'

This is a bit misleading.

`lib/SimpleSAML/Metadata/MetaDataStorageHandler.php:getMetaData()` throws an exception with the message "Metadata for the entity [...entity_id...] expired..." but `modules/saml/lib/Auth/Source/SP:getIdPMetadata()` loses this message resulting in the generic one above.

`getIdPMetadata()` looks elsewhere for metadata if it's not found in `saml20-idp-remote.php` but it would be useful if the "Metadata expired" message got reported to the administrator (it doesn't even get written to the log with debug-level notices).

**Comment by thijskh** [comment] 2015-03-27 15:34
SSP will log a message with level warning even, when it drops an expired entry from the metadata set. However, it does this when loading the metadata, not when processing the request.

This is because currently expiry is checked when loading the metadata, and an expired entry is already rejected at that point. That explains why SSP doesn't tell the user that this entity is expired, because at the point where it would actually be used, the entity in question does not appear in the set of valid metadata anyway.

This could perhaps be changed but of course at the cost of having to check the expiry at every place where the metadata entries are used.

**Comment by trscavo** [comment] 2015-03-27 20:11
Just to muddy the waters a bit, once SSP supports the metadata query protocol, some of your assumptions might change since per-entity metadata is retrieved at the point it is actually needed.

**Comment by tvdijen** [comment] 2018-12-11 23:01
I think @ 2018 we support the metadata query protocol? Is this still relevant?

**Comment by tvdijen** [comment] 2019-05-17 06:55
Related: https://github.com/simplesamlphp/simplesamlphp/issues/747

**Comment by philltran** [comment] 2020-08-07 04:44
I agree that the reported error message is misleading as I just spent quite some time troubleshooting my "missing" entityID from the metadata that was expired.

If letting the error message from `lib/SimpleSAML/Metadata/MetaDataStorageHandler.php:getMetaData()` to show proves too difficult, can we change the error message from  `modules/saml/lib/Auth/Source/SP:getIdPMetadata()` as a stop gap? Perhaps say something like 

> SimpleSAML_Error_Exception: Could not find the metadata of an IdP with entity ID '...entity_id...'. Either the metadata does not exist or the entry is expired.

**Comment by thijskh** [comment] 2020-08-07 10:10
@philltran Which version are you using?

Since 1.18 it should show "Caused by: Exception: Metadata for the entity [https://example.nl/authentication/sp/metadata] expired 908 seconds ago.", that is what it does for me when testing.

If it does not for you we need to fix this further. Otherwise it's fixed in 1.18 and we should close this issue.

**Comment by philltran** [comment] 2020-08-07 15:45
HI. I am using 1.18.7

You are correct that on `/simplesaml/module.php/core/frontpage_federation.php`  the error message about expiration shows. I did not see that previously. 

I was attempting to test the authentication at `/simplesaml/module.php/core/authenticate.php`. The error message here shows `SimpleSAML_Error_Exception: Could not find the metadata of an IdP with entity ID '...entity_id...'`

**Comment by tvdijen** [comment] 2020-08-07 16:46
The issue is that at the point of authentication, the expired metadata is already discarded... So we cannot report about it and you get the unknown entityid error...  We should probably add a callback to the method collecting the metadata so that in this particular case we can include the expired ones.. I'm pretty sure there's an open issue on that..

**Comment by tvdijen** [comment] 2020-08-07 16:50
Ah, so I brought up the issue and made it someone else's issue and they didn't really acted on it ;)
https://github.com/simplesamlphp/simplesamlphp/issues/747

**Comment by thijskh** [comment] 2020-08-07 19:01
Ah ok. I get "Caused by: Exception: Metadata for the entity [https://example.nl/authentication/sp/metadata] expired 908 seconds ago.", that is what it does for me when testing." when trying to use the entity for actual authentication.

So perhaps we can improve further by extending this handling to the place you encountered it (auth test).

**Comment by philltran** [comment] 2020-08-07 19:16
Thanks for all your poking around on this. I appreciate your help.

I actually did see #747 before I landed on this issue to comment on. I figured that one was specifically about the federation frontpage. 

If I get a chance I can try to make a PR for this. 

Thanks again.

**Comment by tvdijen** [comment] 2020-08-07 19:33
We love poking around.. That's what we signed up for :D

It's actually a matter of software architecture...   At the point we 'get metadata' we already receive a filtered set with the expired ones discarded.. That's why you see 'unknown entity id'...   The expired one is not part of the set..
I still feel like we can fix this with a callback filter... I want to be able pull all the metadata and then decide which ones I want to use.. I don't want it to be filtered..

**Comment by thijskh** [comment] 2020-08-19 08:34
So I've reviewed the situation:

1. The admin/federation panel already correctly shows entities that have expired (since 1.18+)
2. Using any SP that is expired will already show a specific exception "Metadata for the entity [https://example.nl/authentication/sp/metadata] expired 908 seconds ago." (since 1.18+)
3. Using any IdP that is expired would still show the "Metadata not found exception".
4. The discovery dropdown (e.g. in auth source test) does not include expired entities.

I fixed 3. on master just now; the more specific exception was generated but swallowed by a try/catch block. This was easy to fix in master. On 1.19, this is less easy because the try/catch block existed to facilitate trying saml20 first and then shib13. I think it's not worth refactoring that entirely as that code has gone in master. Especially because the problem will be evident when looking in admin/federation. For master we now have pretty good warning against expired entities.

I think 4. might actually be more like intended behaviour. Not sure we should list entities that are expired in the discovery. This is more a UI question. If this is desired perhaps a separate issue/PR about that is better.

For now I think it's acceptable to close this as it's solved in broad strokes in 1.18 (visible in admin interface and speciifc exceptions for expired SPs) and solved more completely in master (also specific exceptions for expired IdPs).

**Closed by thijskh** 2020-08-19 08:34 UTC
Labels: enhancement, low
