### ISSUE TITLE
Azure AD 'Non Library' applications now require SignOnURL in SP metadata

### ISSUE THREAD

**Issue by dombenson** [simplesamlphp/simplesamlphp#1336] opened 2020-06-09 18:08 UTC
When creating a custom application in Azure AD (add as non-library), uploading metadata XML generated by simplesamlphp leads to an error as the interface considers 'signOnUrl' to be a mandatory field.

AFAICT, there is no genuine standard for this, but it looks like MS have coopted md:SingleSignOnURL in the context of an SP to provide this.

Whilst this doesn't seem strictly standards-compliant, it would definitely be useful for interoperability to be able to produce metadata accepted by Azure AD, as it is a very widely used SAML2 IdP.

I have a candidate change (based on adding an auth sources config parameter 'azure.signOnUrl') on a branch of my fork. I haven't simply submitted it as a PR as it notably requires a supporting change to the underlying saml2 library (I also have this change in a branch).

On the simplesamlphp branch I added the option and a test for it that skips if the saml2 library has not yet been updated (and a runtime warning), so if this is accepted as a change then it can be modestly decoupled in release terms.

**Comment by tvdijen** [comment] 2020-06-09 18:23
I'm not sure I follow..   You have a SimpleSAML SP and you want to connect it to an Azure AD IDP?

**Comment by dombenson** [comment] 2020-06-09 18:43
Yes, that is the scenario.
When setting up the Azure AD IdP, if you provide metadata XML from the SimpleSAML SP then you get this error:

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/15360130/84186733-db50c800-aa88-11ea-90e1-9533d4358e28.png">
 
However if the metadata is modified to add
`<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://samlsp.example.com/samllogin"/>`
then the metadata upload is accepted:

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/15360130/84187032-5b772d80-aa89-11ea-8be5-fca9193a4af3.png">

**Comment by tvdijen** [comment] 2020-06-09 19:20
What's the (i) saying next to the Sign on URL?  It doesn't really make sense in the context of an SP..

To be honest, I'm not really excited to break standards compliance... MS keeps getting away with that way too often...

**Comment by tvdijen** [comment] 2020-06-09 19:51
Found this issue that suggests the issue is occurring recently:
https://github.com/MicrosoftDocs/azure-docs/issues/56475

**Comment by dombenson** [comment] 2020-06-09 20:08
<img width="527" alt="image" src="https://user-images.githubusercontent.com/15360130/84193930-215f5900-aa94-11ea-908a-08eec7c82ef4.png">

If you don't provide a value for the field, then SP-initiated SSO does fail (some sort of test is performed against the initiator URL vs the value configured; it seems to be at least a weak match. Possibly domain-based. I haven't got conclusive results fo what exactly is required.

I agree that there is a relatively recent Azure AD change involved - I don't know exactly when, but some time in the last few months since I previously tested it.

My proposed change would have it as a config field of `azure.signOnUrl` for the auth source (on the basis that it is a vendor-specific rather than standards-based setting). I agree with not wanting to break standards compliance in general, but it would definitely be helpful to be able to provide it via metadata, as the various users connecting a single application to their respective Azure AD tenant are generally not very familiar with the details, so as an application maintainer it is preferable to make it 'just work'

**Comment by tvdijen** [comment] 2020-06-09 20:14
As I commented in the linked issue, MS should just define a metadata extension.. They exist for exactly this purpose.. Let's see how they respond.

**Comment by tvdijen** [comment] 2020-06-09 20:37
They let me know that it's a bug in the portal and it will be fixed by the end of the week.
Let me know if they actually fixed the issue..
If they want to pull this from the metadata, they should implement http://docs.oasis-open.org/security/saml/Post2.0/sstc-request-initiation-cs-01.pdf

**Comment by tvdijen** [comment] 2020-06-17 09:56
@dombenson They say it's fixed

**Closed by tvdijen** 2020-06-17 09:56 UTC
