### ISSUE TITLE
thumbnailPhoto no longer shows up

### ISSUE THREAD

**Issue by cyndih** [simplesamlphp/simplesamlphp#456] opened 2016-09-02 20:11 UTC
We're sending thumbnailPhoto from our IdP. With version 1.13.2, thumbnailPhoto shows up when going to /simplesaml and testing authentication sources. From 1.14.0 on, currently running the latest, 1.14.6, thumbnailPhoto is blank. Any ideas?

Thanks.

**Comment by tvdijen** [comment] 2016-09-02 22:29
I assume you are referring to the thumbnailPhoto attribute in Active Directory? A little more info would be useful..
Anyway, there is code that discards LDAP-attributes that exceed a certain maximum size.. If that's the case, you should see warnings in your logfile...

**Comment by cyndih** [comment] 2016-09-03 11:57
Yes, thumbnailPhoto in Active Directory. We use PingFederate and are sending the thumbnailPhoto attribute in the SAML token. The thumbnailPhoto shows up just fine in version 1.13.2 of simplesamlphp, viewed in test authentication sources of the simplesaml test page. But in 1.14.0 and above, currently we're on 1.14.6, thumbnailPhoto is blank.

**Comment by tvdijen** [comment] 2016-09-03 13:06
Okay, so you're using SimpleSAMLphp as an SP, PingFederate as an IdP.. That pretty much rules out my earlier comment, since you're not using the SSP LDAP module.
Are you sure that your IdP is still sending the thumbnailPhoto attribute?? Have you made a trace with SAML-tracer for example?

**Comment by thijskh** [comment] 2016-09-03 15:41
What does the XML of the SAML assertion look like? More specifically the attribute containing the thumbnail?

**Comment by cyndih** [comment] 2016-09-03 20:15
Yes, I'm sure. It's there, but blank.

**Comment by jaimeperez** [comment] 2016-09-05 07:39
Hi @cyndih,

Can you be a bit more specific, please? Have you verified that the IdP is sending the attribute with SAML tracer? When you say _but blank_, does that mean that they are sending the attribute without a value? If that's not the case (meaning, you have verified that the IdP is sending the attribute with the corresponding value in the SAML response), can you please paste the response here?

Moreover, have you checked both the web server logs, and SimpleSAMLphp log file?

**Comment by cyndih** [comment] 2016-09-06 13:54
I have verified the IdP is sending the thumbnailPhoto attribute with SAML tracer. When I say but blank I'm referring to the /simplesaml installation page, authentication tab, test configured authentication sources, default-sp, log into IdP, the results that are returned, for thumbnailPhoto are displayed with no value. The other values are filled out, for example, username, mail, etc. The value for thumbnailPhoto is there in SAML tracer. And if I revert back to simplesamlphp 1.13.2, there is a value for thumbnailPhoto. But when I change to to any 1.14.X version, thumbnailPhoto shows on that test page as blank.

Here is the result for SAML trace. saml:AttributeValue></saml:Attribute><saml:Attribute Name=\"thumbnailPhoto\" NameFormat=\"urn:oasis:names:tc:SAML:2.0:attrname-format:basic\"><saml:AttributeValue xsi:type=\"xs:string\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><![CDATA[ï¿½ï¿½ï¿½ï¿½??JFIF?????`?`??ï¿½ï¿½?C???????????\t\t?\n??\r????????????????? $.' \",#??(7),01444?'9=82<.342ï¿½ï¿½?C?\t\t\t????\r\r?2!?!22222222222222222222222222222222222222222222222222ï¿½ï¿½????ï¿½?ï¿½??\"???????ï¿½ï¿½????????????????????????????\t\n?ï¿½ï¿½?ï¿½????????????????}????????!1A??Qa?\"q?2ï¿½ï¿½ï¿½?#Bï¿½ï¿½?Rï¿½ï¿½$3brï¿½\t\n?????%&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyzï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½????????????????????????????\t\n?ï¿½ï¿½?ï¿½????????????????w???????!1??AQ?aq?\"2ï¿½??Bï¿½ï¿½ï¿½ï¿½\t#3Rï¿½?brï¿½\n?$4ï¿½%ï¿½????&'()*56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyzï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½????????????ï¿½ï¿½pï¿½Xsï¿½jï¿½ï¿½ï¿½5ï¿½a){Hï¿½ï¿½?ï¿½ï¿½ï¿½ï¿½yOsï¿½ï¿½?ï¿½ï¿½Ûªï¿½mï¿½N??iï¿½ï¿½ï¿½ï¿½)ï¿½Lï¿½ï¿½1UÕ³JÇ¸ï¿½pf?ï¿½ï¿½ï¿½mï¿½oï¿½\\ï¿½zï¿½<LNï¿½~{?ï¿½\\ï¿½ï¿½ï¿½VPï¿½e`?vï¿½Zï¿½ï¿½ï¿½ï¿½ï¿½ï¿½bBï¿½ï¿½Xï¿½oï¿½Qï¿½ï¿½1Pï¿½kï¿½ï¿½tï¿½S[ï¿½?ï¿½ï¿½ï¿½?ncï¿½???ï¿½?(?ï¿½'-Þ´Q!ï¿½Sï¿½ï¿½ï¿½ï¿½wï¿½kï¿½ï¿½ï¿½?Æ°mï¿½ï¿½ï¿½ï¿½ï¿½kï¿½ï¿½é°ï¿½ï¿½ï¿½ï¿½ï¿½Ü¶?ï¿½Ò?A;ï¿½ï¿½gï¿½ï¿½6ï¿½EMï¿½6oï¿½Tï¿½Þoï¿½Ø¬lï¿½?*ï¿½ï¿½ï¿½zWï¿½ï¿½8Yï¿½3ï¿½ï¿½Jï¿½4?~]:eï¿½Wi-ï¿½??ï¿½CZï¿½ï¿½}?{}ï¿½ï¿½ï¿½Lï¿½!Ð¯?ï¿½3iwï¿½Z)ï¿½Aï¿½iï¿½)#??×¢\"ï¿½ï¿½ï¿½ï¿½ï¿½\rï¿½ï¿½|ï¿½eï¿½ï¿½Pï¿½\r×ï¿½-Jï¿½8?ï¿½ï¿½ï¿½ï¿½ï¿½(ï¿½ï¿½ï¿½nä«©Ý¸uï¿½fï¿½ï¿½ï¿½ï¿½?ï¿½/ï¿½ï¿½?Æ»?4ï¿½ï¿½-ï¿½@?ï¿½#ï¿½;ï¿½\"/Wï¿½Ìcï¿½ï¿½?6\tï¿½Wï¿½ï¿½ï¿½VIï¿½ï¿½Fï¿½ï¿½bï¿½?}k?ï¿½ï¿½ï¿½?ï¿½?=j]ï¿½ï¿½ï¿½ï¿½ï¿½H?Öï¿½Åï¿½?hï¿½??fï¿½-ï¿½&r???ï¿½_?ï¿½Æ°ï¿½ï¿½ï¿½A9ï¿½Ex×ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½?8Aï¿½5ï¿½??uEHá´ï¿½b?>=;Wï¿½ï¿½H$ï¿½Øï¿½ï¿½?ï¿½ï¿½vï¿½?ï¿½Õï¿½ï¿½ï¿½i?\nï¿½ï¿½ï¿½ï¿½ï¿½#V%ï¿½?+ï¿½Ó¼?ï¿½Lï¿½#ï¿½PkNdï¿½ï¿½ï¿½1fï¿½d?ï¿½?Æ ï¿½Nï¿½i?Bï¿½}+ï¿½m|? aï¿½?ï¿½JÖÃ[ï¿½?qY:ï¿½ï¿½ï¿½4Yï¿½wvï¿½C?B?aï¿½MIï¿½~ï¿½HÈzï¿½ï¿½Yï¿½=?r%^ï¿½=+ï¿½Y>rï¿½ï¿½ï¿½ï¿½jï¿½+ï¿½8Yï¿½Oï¿½ï¿½ï¿½ï¿½l.?ï¿½Éï¿½ï¿½ï¿½+ï¿½Wï¿½ï¿½@ï¿½?y<?ï¿½ï¿½\t? ï¿½?bï¿½ï¿½MiXï¿½ï¿½&ï¿½aï¿½Öï¿½ï¿½?Mï¿½Ôï¿½ï¿½?ï¿½sw?ï¿½Å¥ï¿½w4ï¿½ï¿½rï¿½ï¿½ï¿½ï¿½ï¿½ï¿½z5Cblï¿½T?m?ï¿½ï¿½??ï¿½x5ï¿½ï¿½\"ï¿½pï¿½ï¿½8?)ï¿½ï¿½3ï¿½6YV(ï¿½F`?FNi3ï¿½`xï¿½Pï¿½?ï¿½Ñ©?ï¿½!Gï¿½ï¿½!lyï¿½u&ï¿½ï¿½ï¿½ï¿½cï¿½ï¿½?ï¿½?+ï¿½\\ï¿½Êï¿½ï¿½p?ï¿½ZÚ¤ØV=ï¿½?Vï¿½ï¿½ï¿½ï¿½ï¿½&ï¿½P?ï¿½ï¿½gï¿½ï¿½ï¿½Fï¿½ï¿½]ï¿½^?ï¿½ØµHï¿½Wï¿½#8ï¿½ï¿½ï¿½ï¿½$?@?=ï¿½ï¿½W??ï¿½ï¿½}:ï¿½ï¿½?ï¿½ï¿½e>ï¿½ï¿½+ï¿½gJI?B\rï¿½ï¿½*\t??ï¿½Rï¿½ï¿½8ï¿½8ï¿½ï¿½ï¿½ï¿½ï¿½???Eï¿½?Sï¿½???ï¿½ï¿½s^kï¿½Yï¿½ï¿½ï¿½mï¿½r{×¬ï¿½=ï¿½Dï¿½2ï¿½uï¿½xï¿½-ï¿½mï¿½ï¿½ï¿½,ï¿½ï¿½]6ï¿½3ï¿½?kï¿½>ï¿½?_ï¿½:ï¿½ï¿½#iï¿½ï¿½ï¿½#\\ï¿½V;6%`xï¿½<5*?[ï¿½nVLï¿½Ï¯Zï¿½OCï¿½ï¿½ï¿½_ï¿½jï¿½tjï¿½Nï¿½ï¿½ï¿½ï¿½?ï¿½?ï¿½+rï¿½ï¿½ï¿½O,&???,?ï¿½?ï¿½sï¿½Yï¿½?ï¿½?Sï¿½rï¿½ï¿½ï¿½ï¿½J)(ï¿½saâ`ï¿½Fiï¿½ï¿½ï¿½?ï¿½?mOï¿½\rï¿½ï¿½_ï¿½×¡M2ï¿½?ï¿½ï¿½\nï¿½&ï¿½SXï¿½7??ï¿½ï¿½dï¿½fï¿½E#ï¿½ï¿½Ik)I=pkï¿½ï¿½ï¿½R/ï¿½ï¿½?Jï¿½?$\nï¿½/W}ï¿½?ï¿½Gï¿½ï¿½Dï¿½mGï¿½#Ö±?ï¿½sï¿½Ò£ï¿½EOVaï¿½\"ï¿½ï¿½ï¿½\r?ï¿½ï¿½Og<ï¿½ï¿½?ï¿½ï¿½È½Hï¿½%ï¿½?ï¿½<ï¿½ï¿½-.\tï¿½ï¿½ï¿½Iiï¿½5ï¿½ï¿½Y?Hï¿½qï¿½T{ï¿½-ï¿½3ï¿½Ó§{ï¿½1?1Ö±5{ï¿½\rï¿½@ï¿½cgSï¿½ï¿½Òï¿½ï¿½ï¿½×\nÇ½ï¿½ï¿½ï¿½ï¿½:?ï¿½ï¿½É¨ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Å¹bdï¿½,ï¿½ï¿½MAï¿½?ï¿½?)>ï¿½9ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½p@ï¿½ï¿½ti ï¿½ï¿½ï¿½ï¿½)ï¿½ï¿½ï¿½Vï¿½ï¿½ï¿½mï¿½qï¿½?+ï¿½5&ï¿½pmï¿½;yï¿½ï¿½ï¿½3ï¿½4ï¿½ï¿½?ï¿½ï¿½5Q\t??ï¿½lï¿½cï¿½fzÎ´cï¿½Fï¿½ï¿½Qï¿½\"$ï¿½ï¿½?4ï¿½\nï¿½ï¿½RSuï¿½Yï¿½2Å¡?ï¿½jï¿½ï¿½ì»ï¿½Ê®ï¿½ï¿½ï¿½~ï¿½ï¿½ï¿½wï¿½ï¿½?ï¿½j:ï¿½AKÞ?ï¿½(ï¿½ï¿½.ï¿½)?ï¿½ï¿½Wï¿½_ÉÇ©ï¿½Dï¿½ï¿½ï¿½?ï¿½ï¿½?SÈ¯2ï¿½pï¿½?{ï¿½ï¿½?'ï¿½Zï¿½ï¿½$t??ï¿½?ï¿½Ytï¿½Cqï¿½q^szÑ?ï¿½ï¿½ï¿½=6?ï¿½ï¿½ï¿½U{ï¿½ï¿½ï¿½?ï¿½ï¿½vï¿½ï¿½ï¿½?Nï¿½ï¿½ï¿½ï¿½{ï¿½Îï¿½Gï¿½Dï¿½zï¿½??ï¿½?\"ï¿½ï¿½=N+ï¿½[?Ï?vï¿½ï¿½ï¿½m ï¿½ï¿½Pï¿½?yï¿½aï¿½ï¿½ï¿½Jï¿½M?Sï¿½Mï¿½ï¿½?Qï¿½'Òï¿½uï¿½ï¿½ï¿½ï¿½ï¿½w$?,Uï¿½cï¿½ï¿½ï¿½\"??sYzï¿½_ï¿½Éï¿½ï¿½$ï¿½ï¿½ï¿½Jï¿½ï¿½? wï¿½ï¿½Nï¿½uï¿½?cï¿½bï¿½ï¿½ï¿½\\ï¿½<ï¿½Q8ï¿½oï¿½ï¿½ï¿½8?ï¿½ï¿½7ï¿½<ï¿½'ï¿½5Pï¿½ï¿½ï¿½â» ï¿½<ï¿½Zï¿½ï¿½ZQ{ï¿½Ç¶~ï¿½ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½>?ï¿½)?ï¿½{ï¿½Eu[ï¿½ï¿½Ee6ï¿½5ï¿½ï¿½?Ñ³Kï¿½)ï¿½ÒÄ¡ï¿½?ï¿½?zÔï¿½;Sï¿½ï¿½?ï¿½ï¿½S?ï¿½<c~&ï¿½??ï¿½Cï¿½qï¿½ï¿½ï¿½?ï¿½Zï¿½ï¿½ï¿½ï¿½]O?$ï¿½Xï¿½ï¿½v=ï¿½ï¿½ï¿½ï¿½Èï¿½oï¿½uï¿½ï¿½ï¿½Óï¿½U'%?1\\ï¿½Íï¿½}M]ï¿½ï¿½ï¿½ï¿½Úï¿½ï¿½@V9?Öï¿½ï¿½M9ZG{ujï¿½3$??ï¿½ï¿½*ï¿½ï¿½.ï¿½+ï¿½?ï¿½ï¿½\tï¿½ï¿½ï¿½?zï¿½as$<ï¿½ï¿½ï¿½ï¿½?ï¿½y?zï¿½*ï¿½Fw%uï¿½ï¿½ogï¿½ï¿½ï¿½dï¿½6ï¿½ï¿½ï¿½ï¿½ï¿½?ï¿½ï¿½?Jï¿½ï¿½6ï¿½<ï¿½jï¿½F(ï¿½Pï¿½ï¿½ï¿½ï¿½5Fï¿½)?9jz ï¿½ï¿½iï¿½ï¿½Zï¿½ï¿½3Dï¿½Â§?ç©uï¿½ï¿½?Fï¿½>ï¿½ï¿½ï¿½v1~ï¿½9ï¿½\rkQUï¿½'ï¿½8Qï¿½Fï¿½C9ï¿½ï¿½Fï¿½aï¿½ `ï¿½ï¿½ï¿½ï¿½Õ»Ã¸ï¿½Î«ï¿½ï¿½ï¿½~ï¿½W\\?ï¿½?Ö¦Ç$ï¿½{ï¿½ï¿½q^ï¿½ï¿½=?yvï¿½#E|?pC?Waï¿½ï¿½7ï¿½g5ï¿½ï¿½&ï¿½Oaï¿½ï¿½ï¿½6ï¿½_iï¿½?HMaï¿½ï¿½?ï¿½7ï¿½Zï¿½zï¿½ï¿½?ï¿½`ï¿½ï¿½ï¿½#ï¿½`l|ï¿½$ï¿½h?%ï¿½d-w1ï¿½ï¿½ï¿½ï¿½ï¿½]ï¿½dÖï¿½ï¿½Dï¿½ï¿½ãï¿½ï¿½soï¿½m?ï¿½ï¿½ï¿½ï¿½ZCï¿½Aï¿½Qrï¿½o?ï¿½{?4Íï¿½Jï¿½nÙ¸?ï¿½;ï¿½ï¿½Vï¿½ï¿½Ñï¿½ï¿½kR@V+ï¿½ï¿½ï¿½ï¿½WUms?ï¿½u`Qï¿½ï¿½]>;ï¿½?$rT?EQï¿½wï¿½9@ï¿½?(<?W?ï¿½ï¿½e)ï¿½ï¿½q,>Pï¿½gï¿½Yï¿½3\"ï¿½?/ï¿½Zã­xï¿½xsï¿½lTW:ï¿½ï¿½ëµï¿½^)$lï¿½^ï¿½ï¿½ï¿½ï¿½,ï¿½x?ï¿½W?sï¿½I}ï¿½)bBï¿½ï¿½^ï¿½R!b{ï¿½-ï¿½ï¿½?N?Õ½?ï¿½ï¿½ï¿½RNï¿½ï¿½Z?wBp;?Rï¿½ï¿½&ï¿½ï¿½\"Iï¿½T^ï¿½S ï¿½ï¿½\\ï¿½Ð±?ï¿½yOï¿½ï¿½ï¿½';mdqÖ´ï¿½ï¿½dï¿½ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½MRï¿½rï¿½1??ï¿½Õ¼ï¿½Xï¿½Üï¿½V*Nï¿½W?:Nf]n[Kï¿½ï¿½{ï¿½ï¿½ï¿½ï¿½ï¿½??}ï¿½,?ï¿½?ï¿½?ï¿½ï¿½^??ï¿½?ï¿½<ï¿½wï¿½?ï¿½ï¿½ï¿½rï¿½(Xï¿½ï¿½Aï¿½ZB?bnÄ]ï¿½?ï¿½ï¿½\r*rï¿½\tï¿½V_ï¿½mï¿½ï¿½Vï¿½wgÜï¿½ï¿½ï¿½ï¿½eï¿½ï¿½Qï¿½\n?}sTcbï¿½ï¿½;Öï¿½.:bï¿½]\nï¿½?5qï¿½XLï¿½??jï¿½ï¿½ï¿½??PVï¿½Õª\\Gï¿½ï¿½$g5ï¿½dï¿½ï¿½*ï¿½?ï¿½ï¿½Yjj?Qï¿½ï¿½1ï¿½ï¿½-HÙAï¿½B4ï¿½ï¿½@9ï¿½G=ï¿½DÉ­ï¿½Ñ¸Êï¿½u?ï¿½Ü®Tï¿½ï¿½ï¿½ksï¿½ï¿½\\?+??\"ï¿½p?ï¿½ï¿½#ï¿½xï¿½Ú²ï¿½\tï¿½ï¿½I9æ¶ï¿½g<ï¿½#uï¿½ï¿½??ï¿½hï¿½=ï¿½[ï¿½ï¿½Qï¿½ï¿½dï¿½1ï¿½ë¸jï¿½ï¿½3ï¿½Eï¿½<?ï¿½ï¿½ï¿½?ï¿½?ï¿½Eï¿½ï¿½Tï¿½ï¿½ï¿½)(ï¿½ï¿½Lï¿½??ï¿½ï¿½ï¿½ï¿½ï¿½I#ï¿½^}ï¿½ï¿½ï¿½sï¿½jï¿½ï¿½Ý¬ï¿½Kï¿½?ï¿½W?w:/ï¿½ï¿½Ú¦ï¿½ï¿½ï¿½ï¿½?ï¿½=Cï¿½#ï¿½ï¿½\tï¿½/!8ï¿½jkï¿½?ï¿½ï¿½?}ï¿½ï¿½dIÖ» ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½Rï¿½ï¿½8Ý·ï¿½UXï¿½?ï¿½Jï¿½|}jï¿½&ï¿½?/!ï¿½ï¿½ï¿½oY??3ï¿½)ï¿½ï¿½ï¿½>ï¿½ï¿½Pï¿½?ï¿½ï¿½ï¿½)?ï¿½ï¿½?ï¿½Ðgiï¿½ï¿½??I?ï¿½>ï¿½iXuOï¿½LÖ*/Sï¿½ï¿½C$\"@~`?EOï¿½\"ï¿½?ï¿½ï¿½ï¿½ï¿½ï¿½wï¿½ï¿½Ç¸ï¿½Vtï¿½1.ï¿½,ï¿½ï¿½Bï¿½\\6r0ï¿½ï¿½Ôï¿½aï¿½ï¿½3ï¿½?ï¿½ï¿½Mi?ï¿½dï¿½9?ï¿½ï¿½ï¿½=ï¿½?ï¿½ï¿½[ß¾ï¿½Jï¿½nï¿½ï¿½[SZ\n{?!ï¿½???ï¿½Rï¿½Ú ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½]]

**Comment by cyndih** [comment] 2016-09-06 15:28
Here is the results from simplesamlphp log:
Sep 06 11:21:04 simplesamlphp DEBUG [1a61c76bb0] Session: Valid session found with 'default-sp'.
Sep 06 11:21:04 simplesamlphp DEBUG [1a61c76bb0] Template: Reading [/var/simplesamlphp/dictionaries/status]
Sep 06 11:21:04 simplesamlphp DEBUG [1a61c76bb0] Template: Reading [/var/simplesamlphp/dictionaries/attributes]
Sep 06 11:21:04 simplesamlphp ERROR [1a61c76bb0] SimpleSAML_Error_Exception: Error 2 - htmlspecialchars() expects parameter 1 to be string, object given
Sep 06 11:21:04 simplesamlphp ERROR [1a61c76bb0] Backtrace:
Sep 06 11:21:04 simplesamlphp ERROR [1a61c76bb0] 6 /var/simplesamlphp/www/_include.php:83 (SimpleSAML_error_handler)
Sep 06 11:21:04 simplesamlphp ERROR [1a61c76bb0] 5 [builtin] (htmlspecialchars)
Sep 06 11:21:04 simplesamlphp ERROR [1a61c76bb0] 4 /var/simplesamlphp/templates/includes/attributes.php:75 (present_attributes)
Sep 06 11:21:04 simplesamlphp ERROR [1a61c76bb0] 3 /var/simplesamlphp/templates/status.php:34 (require)
Sep 06 11:21:04 simplesamlphp ERROR [1a61c76bb0] 2 /var/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:577 (SimpleSAML_XHTML_Template::show)
Sep 06 11:21:04 simplesamlphp ERROR [1a61c76bb0] 1 /var/simplesamlphp/modules/core/www/authenticate.php:52 (require)
Sep 06 11:21:04 simplesamlphp ERROR [1a61c76bb0] 0 /var/simplesamlphp/www/module.php:137 (N/A)

**Comment by jaimeperez** [comment] 2016-09-06 15:56
Hi @cyndih,

I'm afraid I can't see much in that excerpt you pasted from the SAML response. Can you edit your message to include the entire `<saml:Attribute>` element with its contents, just as you see it in the SAML tracer?

Apart from that, have you tried the latest version, 1.14.8? Note that 1.14.6 (which you say you are running) is **not** the latest version available. As a matter of fact, some bugs were fixed in that code between those versions, so I believe the bug you are hitting was already fixed and the problem is essentially that you are not running the latest stable version.

**Comment by cyndih** [comment] 2016-09-06 16:03
1.14.6 is the latest from simplesamlphp website.

**Comment by jaimeperez** [comment] 2016-09-06 16:07
Uhm, no [it's not](https://simplesamlphp.org/download):

>Here you will find the packages with the latest SimpleSAMLphp stable version:
>
> * Latest stable version (1.14.8)
>    Released: 2016-08-23.
>
>    SHA256 checksum: fc13d3b4cd29445124daeefd382d41643e64fa8ab37af31eb24c5d9e1c1aa92b

😕

**Comment by cyndih** [comment] 2016-09-06 16:56
I will try with the latest version. I was looking here for the latest version. https://simplesamlphp.org/

**Comment by jaimeperez** [comment] 2016-09-06 17:14
Oh, that's true, I forgot to add some news to the front page with the last releases. In any case, the links there all point to the downloads page, where it is clearly stated that 1.14.8 is the latest version. How did you download 1.14.6?

**Comment by cyndih** [comment] 2016-09-06 17:23
I downloaded it a while back when it was the stable version. :)

**Comment by cyndih** [comment] 2016-09-06 17:57
I unzipped the latest version and removed config and metadata and copied in the old one. I get a 500 error now when I go to the simplesaml test page.

**Comment by tvdijen** [comment] 2016-09-06 18:39
That could mean a whole bunch of things.. What does your webserver's error log say?

**Comment by cyndih** [comment] 2016-09-06 19:46
Argument 1 passed to SimpleSAML_Session::load() m                                                                                                                                                             ust be an instance of SimpleSAML_Session, boolean given, called in /var/simplesa                                                                                                                                                             mlphp/lib/SimpleSAML/Session.php on line 266 and defined in /var/simplesamlphp/l                                                                                                                                                             ib/SimpleSAML/Session.php on line 378

**Comment by cyndih** [comment] 2016-09-06 20:16
I closed and opened my browser, works now, but still the test page doesn't show the thumbnailPhoto

**Comment by jaimeperez** [comment] 2016-09-06 20:45
Ok, what does the error log say now?

**Comment by cyndih** [comment] 2016-09-06 22:13
No errors in the simplesamlphp log file now.

**Comment by jaimeperez** [comment] 2016-09-07 07:57
That's good, it means there's no bug there any longer.

Now, we can focus on the problem you are experiencing, which is the picture not showing up, and I actually think it's normal. The problem here is that _thumbnailPhoto_ is not a recognized attribute name (I'm not saying it's not common or unusual, just that SimpleSAMLphp does not recognize it), and as such, SimpleSAMLphp has no clue on what to do with it whatsoever. If the attribute was named _jpegPhoto_ instead, then SimpleSAMLphp would handle it as a picture and show it to you, but given the attribute is not recognized and its contents marked (**erroneously**, I'd say) as a string, all it can do is try to display it as a string. Since the contents appear to be the raw binary of the picture (which I'd say is **definitely wrong**), your browser doesn't know how to handle that and displays nothing.

Of course I'm just guessing, since I don't have an Active Directory here to test, but I think I'm not too far from target. If you **really** want the picture to be shown there, try adding a couple of authproc filters to the remote IdP metadata, one to rename the attribute to _jpegPhoto_ (`core:AttributeMap` filter) and another to _base64-encode_ its value (with `core:PHP`, writing the PHP code to convert its value yourself). The picture will then show up.

In any case, this is just an issue in the web interface. The attribute value is there and you can use it in your application. The web interface is only intended for you to test authentication, so it doesn't really matter if the picture shows up or not.

I'm closing the issue now. If you need further help, please send an email to [the mailing list](http://groups.google.com/group/simplesamlphp).

**Closed by jaimeperez** 2016-09-07 07:57 UTC
Labels: needsinfo
