### ISSUE TITLE
$auth->logout( ReturnTo not working

### ISSUE THREAD

**Issue by frank12311** [simplesamlphp/simplesamlphp#390] opened 2016-05-13 13:06 UTC
Hi,

Ive managed to setup a working demo with a test AzureAD. Everything is fine, and I am happy.

When i try to call $auth->logout or $auth->getlogouturl with the ReturnTo parameter setted, i get logged out, but not returned to the URL. I can see the functions are working correct, becouse the URL is being added to the logoutURL, as_logout.php?AuthId=default-sp&ReturnTo=https://sso.mydomain.com/bye.php. However, I stay at the microsoft logout url:

https://login.microsoftonline.com/XXXXXXXXX/saml2?SAMLRequest=XXXXX&RelayState=XXXXX
![090515_2034_singlesigno35](https://cloud.githubusercontent.com/assets/16739295/15248931/19f01068-191d-11e6-9c2c-2e1e236b7c5b.png)

My config has this set:
'trusted.url.domains' => array('sso.mydomain.com'),

Ive been googling a bit around, but cant seem to find the problem. 

Thanks
Frank

**Comment by frank12311** [comment] 2016-05-13 13:12
This would be the Microsoft page

![090515_2034_singlesigno35](https://cloud.githubusercontent.com/assets/16739295/15248931/19f01068-191d-11e6-9c2c-2e1e236b7c5b.png)

**Comment by jaimeperez** [comment] 2016-05-18 13:27
Hi @frank12311!

I would say this is an issue with the third party (Microsoft in this case). If all you see is that the browser stays at the IdP, then they are not sending back a logout response (which doesn't really surprise me). Can you verify with something like [SAMLtracer](https://addons.mozilla.org/en-US/firefox/addon/saml-tracer/) that you are never getting a response back?

**Comment by jaimeperez** [comment] 2016-05-31 08:17
Hi,

I'm closing this, since it is likely an issue on Microsoft's side.

Feel free to comment again to reopen if you have more information that helps us identify a problem.

**Closed by jaimeperez** 2016-05-31 08:17 UTC
Labels: needsinfo

**Comment by jaimeperez** [comment] 2016-07-15 14:12
Hi!

Just a quick note. After some discussions with a colleague who's playing around with Microsoft's login service, I can confirm this is a Microsoft issue. Apparently, they only support a partial SP-initiated logout. They just load the SLO process in a hidden iframe, and after a few seconds, tell the user that logout was successful (without actually checking anything).

In fact, they are (almost) completely ignoring the logout response they receive. As an example, they consider this a valid SAML logout response:

```xml
<LogoutResponse xmlns="urn:oasis:names:tc:SAML:2.0:protocol"/>
```
