### ISSUE TITLE
Support symfony/routing 7.0

### ISSUE THREAD

**Issue by johntheteam** [simplesamlphp/simplesamlphp#2248] opened 2024-09-16 00:57 UTC
**Is your feature request related to a problem? Please describe.**
When upgrading to Lavavel 11 which requires symfony/routing ^7.0, but simplesamlphp/simplesamlphp[v2.2.0, ..., v2.3.2] require symfony/routing ^6.4

**Describe the solution you'd like**
Suggest to have a new major version that supports symfony/routing ^7.0

**Describe alternatives you've considered**
Not use Laravel 11 or any newer version for now, it'll become harder and harder to maintain.

**Comment by tvdijen** [comment] 2024-09-16 10:37
Duplicate of https://github.com/simplesamlphp/simplesamlphp/issues/2164, https://github.com/simplesamlphp/simplesamlphp/issues/2122 and https://github.com/simplesamlphp/simplesamlphp/issues/2008

**Closed by tvdijen** 2024-09-16 10:37 UTC
