### ISSUE TITLE
Web Server rewrite not taken into account to access module web interface

### ISSUE THREAD

**Issue by dweeves** [simplesamlphp/simplesamlphp#1093] opened 2019-04-10 14:26 UTC
## Abstract case 
 - cannot access a module with a web interface (not bound to SAML session) through a server rewrite without redirect to real (module.php/modulename/moduleroute) on a url with parameters.

## Concrete case: 

module selfregister, that allows for handling user registration.
 
## Apache Rewrite Configuration:
`RewriteRule ^/register module.php/selfregister/newUser.php [QSA,L]`

## Why it bothers
In some deployments, the "exposed" url needs to be "polished" (having /register) instead of (/module.php/selfregister/newUser.php) is a valid expectation i think.

## To Reproduce
1. Install a module that has its own web interface
2. create an apache rewrite to this module web interface
3. You'll get a 404 not found (because module does not match initial url)

## Expected behavior
The real module name (selfregister) should be matched using $_SERVER['PATH_INFO'] (which is the apache rewritten url) rather than using the left part of original non apache rewritten URL.

So , having /register able to process module

## Additional context
The problem lies in module detection using $request->getPathInfo() , which uses symfony request class, which tries to be a bit too "smart"

File:
/lib/SimpleSAML/Module.php , method process(), line 123

Real cause:
use of /vendor/symfony/http-foundation/Request.php , which computes the pathinfo from the request uri.

## Current workaround (i.e : not fitting my requirement)
 - Force a real redirect in apache config [R,QSA,L] in the end of the redirect rule line 
  - This is really not what i want, since exposing the "SAML module" internal url which i tried to avoid.

**Comment by tvdijen** [comment] 2019-04-10 14:34
This is a duplicate of https://github.com/simplesamlphp/simplesamlphp/issues/1023

**Comment by dweeves** [comment] 2019-04-10 16:08
submitted PR #1095 to solve this issue

**Closed** 2019-09-16 10:36 UTC
Labels: enhancement, low
