### ISSUE TITLE
Missing SingleLogoutService shouldn't cause an error

### ISSUE THREAD

**Issue by jval** [simplesamlphp/simplesamlphp#677] opened 2017-08-16 11:17 UTC
There's no MUST for a remote SP to provide SingleLogoutService so when it's not given by the remote SP simpleSAMLphp shouldn't cause the error: "Could not find a supported SingleLogoutService endpoint."

**Comment by jaimeperez** [comment] 2017-08-16 11:55
Hi @jval,

SimpleSAMLphp does not require remote SP metadata to include a `SingleLogoutService` endpoint. Could you please tell us when do you get that error, and what are the steps to reproduce?

**Comment by jval** [comment] 2017-08-16 12:54
The error happens when you log out from a remote SP. Maybe it's because our IdP provides SingleLogoutService in its metadata (value ending with "/saml2/idp/SingleLogoutService.php") and some remote SPs (maybe running the shibboleth.net SP) perhaps use it even when they don't use the SAML2 single logout themselves.

**Comment by jaimeperez** [comment] 2017-08-16 13:00
Well, if they are sending you a logout request to the `SingleLogoutService` endpoint of your IdP, then they **do** use SAML2 single logout. I'm not sure it's ok to receive a `LogoutRequest` if you can't send a `LogoutResponse` back, so I don't know if this is a bug or not.

Have you verified with the SP that they don't have an SLO endpoint indeed?

**Comment by jval** [comment] 2017-08-16 13:13
Yes, I have checked the metadata of the SP. This happens when the SP doesn't provide SingleLogoutService in its metadata.

**Comment by jval** [comment] 2017-08-16 13:17
It might be correct for the SP to send a logout request because even when itself doesn't have an endpoint some other SP in the session might.

**Comment by trscavo** [comment] 2017-08-16 13:21
This is a "known issue" in any federation based on metadata. If the SP sends a `LogoutRequest` to an IdP, but the SP does not have a `SingleLogoutService` endpoint in metadata, then an IdP has no choice but to return a SAML error.

The problem is on the SP side. The SP should include a `SingleLogoutService` endpoint in metadata or stop sending an apparently unsupported `LogoutRequest` to the IdP. The rest is an implementation detail, I suppose.

**Comment by jaimeperez** [comment] 2017-08-16 13:38
Thanks for the clarification Tom!

It's exactly what I was thinking, it doesn't make any sense to claim you don't support SLO and use it... In any case, even if we wanted to do something about it, I don't see much that we can do. We got a `LogoutRequest` which we are supposed to reply to, and we don't have a way to do that because we don't have an SLO endpoint registered for that SP.

I guess we could just logout and skip sending the response, but I suspect the SAML standard mandates sending a reply, so I'm closing this ticket for now. Feel free to comment if I'm wrong and there's something we can do indeed.

**Closed by jaimeperez** 2017-08-16 13:38 UTC
Labels: needsinfo
