### ISSUE TITLE
SimpleSAML\Error\MetadataNotFound: METADATANOTFOUND('%ENTITYID%' => '\'1\'')

### ISSUE THREAD

**Issue by aaalexby** [simplesamlphp/simplesamlphp#1359] opened 2020-07-27 16:45 UTC
**Describe the bug**
SimpleSAML\Error\MetadataNotFound: METADATANOTFOUND('%ENTITYID%' => '\'1\'')

**To Reproduce**
1. Edit file '/var/www/simplesaml/metadata/saml20-sp-remote.php'
2. Add new $metadata with index '1'
3. Try to use it.
4. See error:
SimpleSAML\Error\MetadataNotFound: METADATANOTFOUND('%ENTITYID%' => '\'1\'')

$metadata['a'] -  works
$metadata['1a'] - works
$metadata['a1'] - works
$metadata['01'] - works
$metadata['1'] - don't works
$metadata['12345'] - don't works
$metadata['012345'] - works

**Comment by tvdijen** [comment] 2020-07-27 19:48
I can confirm that '0' and '1' are transformed into 0 and 1. This happens when `include()` is being called to load the metadata-file.
Since this is PHP-behaviour, I'm not sure if we can fix this.

**Comment by tvdijen** [comment] 2020-07-27 20:27
https://www.php.net/manual/en/language.types.array.php#language.types.array.key-casts

It's actually documented behaviour for array keys, so I will close this as a wontfix.. No way to work around it.

**Closed by tvdijen** 2020-07-27 20:27 UTC
Labels: wontfix
