### ISSUE TITLE
Deprecated use of new SimpleSAML\Locale\Translate::t(...) at /var/www/html/idp/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:716. The $tag-parameter can only be a string in 2.0.

### ISSUE THREAD

**Issue by kbabioch** [simplesamlphp/simplesamlphp#893] opened 2018-07-24 13:36 UTC
When requesting the `module.php/core/frontpage_config.php` after following the [installation instructions](https://simplesamlphp.org/docs/stable/simplesamlphp-install), the following error/warning is logged:

    Jul 24 15:34:19 fedora28.localdomain simplesamlphp[11194]: 4 [1181ef6f4a] Deprecated use of new SimpleSAML\Locale\Translate::t(...) at /var/www/html/idp/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:716. The $tag-parameter can only be a string in 2.0.

This is probably something that should be fixed eventually.

**Comment by thijskh** [comment] 2018-07-24 13:37
Thanks. Which SSP version is this exactly?

**Comment by kbabioch** [comment] 2018-07-25 07:04
The latest version: 1.15.4

**Comment by dezertol** [comment] 2018-08-10 18:07
We are also seeing this error and because we have 120 authsources it creates a big chunk of logs... 
Is this an issue with formatting the authsource?
We are using something similar to this

$source[$block->authSource] = array(
     'text' => array(
            'en' => $block->description,
            'es' => $block->description,
      ),
'css-class' => 'SAML'
....... etc

Do we need to convert that 'text' into a string, and if so what's the recommended way of handling multi language.

**Comment by roboshim** [comment] 2018-09-20 14:08
Hi all,

the problem "The $tag-parameter can only be a string in 2.0" arise in more modules, even in our module I had to fix the "text" array key to contain directly string instead of array with single "en" key and string.

The problem described in this issue during requesting the "frontpage_config.php" is caused by code in modules/sanitycheck/hooks/hook_frontpage.php (see https://github.com/simplesamlphp/simplesamlphp/blob/v1.16.1/modules/sanitycheck/hooks/hook_frontpage.php line 14).

This incompatibility is already fixed in master https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/sanitycheck/hooks/hook_frontpage.php.

But maybe there are other places, where the code must be fixed, if it use t() function, e.g. https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/sanitycheck/hooks/hook_moduleinfo.php lines 13 and 14?

Regards,

Robert.

**Comment by tvdijen** [comment] 2018-10-20 12:52
We are in the process of moving to a new templating/internationalization system, so this warning is just an indicator that the current way of use will no longer be supported in 2.0...
If you have any custom modules, you're gonna have to migrate them for 2.0

**Closed by tvdijen** 2018-10-20 12:52 UTC
