### ISSUE TITLE
Frontpage_federation does not display expired entities

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#747] opened 2017-12-12 17:37 UTC
This page has logic in place to display and mark expired metadata entities on the frontpage_federation-page, but it appears that this never happens. Actually, expired metadata entities are completely hidden from the view.

A little investigation turned out that MetaDataStorageHandler::getList() filters out any entity that has expired and there really isn't an alternative to get the full unfiltered list of configured entities.

We either need a method to fetch unfiltered entities, or stop filtering them in getList and move that logic to wherever it may be desirable to filter them.

**Comment by thijskh** [comment] 2018-11-21 10:38
Is a duplicate of #183?

**Comment by tvdijen** [comment] 2018-12-11 22:07
It seems so yes.. That one doesn't clearly seem to explain the issue though... Feel free to close either one, as long as it's clear that we need to be able to pull metadata even if it's expired, then I'm fine!

**Comment by tvdijen** [comment] 2018-12-12 10:13
I think I would add a new method with a callback parameter, so that different kinds of filters can be used dynamically (or null for unfiltered).. Then we can at least fix the federation page to show expired entries

**Comment by tvdijen** [comment] 2019-03-14 20:26
I consider this an issue for the new admin module and therefore tagged it for 1.18

**Comment by thijskh** [comment] 2019-07-29 11:05
More of a wishlist thing than a requirement to release 1.18.

**Comment by tvdijen** [comment] 2019-07-29 12:58
Never leave to tomorrow that which you can do today!

**Closed** 2019-07-29 13:52 UTC
Labels: enhancement
