### ISSUE TITLE
unable to set "Comparison" attribute for samlp:RequestedAuthnContext 

### ISSUE THREAD

**Issue by manzolo** [simplesamlphp/simplesamlphp#427] opened 2016-07-29 13:18 UTC
I can't set attribute comparison ("exact", "minimum", "maximum", or "better", exact is default) from parameters to RequestedAuthnContext section. 
In "Assertions and Protocols for the OASIS Security Assertion Markup Language (SAML) V2.0, OASIS Standard, 15 March 2005" in section "3.3.2.2.1 Element <RequestedAuthnContext>" specs you can find it.
I need to set it to minimum.

`https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/lib/Auth/Source/SP.php#L195`

i would to pass : 
`$accr = SimpleSAML\Utils\Arrays::arrayize($state['saml:AuthnContextClassRef']);`
an array like this:
from 
`$ar->setRequestedAuthnContext(array('AuthnContextClassRef' => $accr));`
to
`$ar->setRequestedAuthnContext(array('Comparison' => 'minimum','AuthnContextClassRef' => $accr));`

Is it possible?
Thanks!!

**Comment by jaimeperez** [comment] 2016-08-01 08:25
Hi @manzolo!

No, it's not possible (as of today). You may want to take a look at [this thread](https://groups.google.com/forum/#!topic/simplesamlphp/JKLvHKihEbs).

This is also a duplicate of #409, though I will keep it open as a feature request.

**Comment by manzolo** [comment] 2016-08-01 08:38
Ok @jaimeperez ! It's the exact same problem. I saw the two problems without an answer and i  sent a email to author of thread without response, then i opened this issue. No problem! Good job!!

**Comment by tvdijen** [comment] 2017-12-18 11:31
With the release of 1.15 came the possibility to specify a comparison, so I'm closing this one.

**Closed by tvdijen** 2017-12-18 11:31 UTC
Labels: duplicate, enhancement, low
