### ISSUE TITLE
2.0 assets not installed - empty assets-dir

### ISSUE THREAD

**Issue by krisskals** [simplesamlphp/simplesamlphp#1794] opened 2023-03-24 23:26 UTC
After all, this is a new version of simplesamlphp and we have to go down with versions of libraries released later? After all, this is some kind of misunderstanding? Why was this request closed instead of being resolved with an update?

**Comment by krisskals** [comment] 2023-03-24 23:28
concerns notification #1973

**Comment by krisskals** [comment] 2023-03-24 23:40
And the submission was closed ignoring the main thread As a reminder: 

After installing simplesamlphp using the composer require simplesamlphp/simplsamlphp command, there is no file in the /vendor/simplesamlphp/simplesamlphp/public/assets directory.

**Comment by krisskals** [comment] 2023-03-24 23:44
Maybe simplesamlphp can't be installed via composer, because as you can see it has many disadvantages.... But this is not mentioned in the documentation, and the library is mega outdated and not adapted to the basic requirements?

**Comment by thijskh** [comment] 2023-03-25 07:10
This is an open source project run by volunteers. We are limited in time so currently prioritizing on supporting LTS software. You are very welcome to contribute if you want to improve a certain aspect to align with your requirements.

**Comment by tvdijen** [comment] 2023-03-26 19:44
The upgrade to symfony v6 has already been done in `master` and will be released in a future release.
I tried reproducing the assets-issue, but I couldn't..

`composer init`
`composer require simplesamlphp/simplesamlphp`
`ll vendor/simplesamlphp/simplesamlphp/public/assets/base`  << assets are installed

**Comment by krisskals** [comment] 2023-04-04 06:39
I have done SimpleSAMLphp installation on two different servers and in both cases the `/vendor/simplesamlphp/simplesamlphp/public/assets` directory is empty - no directories or files. At the moment I solved it for myself by manually adding files (from package tar.gz).

**Comment by tvdijen** [comment] 2023-04-04 07:18
Are you upgrading a 1.19 install?

**Comment by krisskals** [comment] 2023-04-04 07:30
No, I am installing the latest clean version 2.0.3.

**Comment by tvdijen** [comment] 2023-04-04 18:59
So help me out here, because I demonstrated the commands I used and I cannot reproduce. What are you doing to get into this situation?

**Comment by krisskals** [comment] 2023-04-04 19:24
It simply installs SimpleSAMLphp using the composer command require simplesamlphp/simplesamlphp. I don't have this library in the vendor and application dependencies, adding it as required. You could say that this is a clean, new installation of the library (version 2.0.3, which is the latest available). There is no content in the assets directory, so there is no style panel. To solve this problem I download the library file as a .tar.gz and add the contents of the directory "manually". I don't know what to write more...

**Comment by tvdijen** [comment] 2023-04-04 19:57
And I don't know what to do anymore without details of your install.. I feel like I'm wasting time chasing a red herring here.

**Comment by krisskals** [comment] 2023-04-04 20:55
The composer clear-cache command does not solve the problem. Still the `/vendor/simplesamlphp/simplesamlphp/public/assets` directory is empty :/.

**Comment by krisskals** [comment] 2023-04-04 21:01
`composer show `
```

simplesamlphp/assert                    v0.8.0  A wrapper around webmozart/assert to make it useful beyond checking method arguments
simplesamlphp/composer-module-installer v1.3.4  A Composer plugin that allows installing SimpleSAMLphp modules through Composer.
simplesamlphp/saml2                     v4.6.6  SAML2 PHP library from SimpleSAMLphp
simplesamlphp/simplesamlphp             2.0.3   A PHP implementation of a SAML 2.0 service provider and identity provider.
simplesamlphp/simplesamlphp-assets-base v2.0.4  Assets for the SimpleSAMLphp main repository
```

**Comment by tvdijen** [comment] 2023-04-04 21:06
I'm baffled, can't reproduce this and won't spend any more time on this issue until we have more clues.

**Comment by krisskals** [comment] 2023-04-04 21:13
OK. I understand. Thank you for your answers. I don't know what more I can write. The application that for a short time in the design assumptions is to change the method of authentication and the choice was simpleSAMLphp. Everything works fine, except for the lack of content in the /public/asserts directory after a clean install using the composer require simplesamlphp/simplesamlphp command. Maybe someone else, after a new installation will report the problem and the matter will clear up....

**Comment by tvdijen** [comment] 2023-04-04 21:23
Maybe https://groups.google.com/g/simplesamlphp/c/o1GCTzl7chQ/m/iTDh1vvKAQAJ
What happens if you run `composer install` after the initial installation?

**Comment by krisskals** [comment] 2023-04-04 21:42
The composer intall in the application's root directory did not work properly. Still an empty directory. But calling `composer install ` after entering `/vendor/simplesamlphp/simplesamlphp` worked positively and the dependencies were reinstalled along with the contents of the `/vendor/simplesamlphp/simplesamlphp/public/asserts` directory. A strange situation...

**Comment by tvdijen** [comment] 2023-04-04 22:36
What OS and PHP-version are involved here?

**Comment by krisskals** [comment] 2023-04-05 06:08
CentOS Linux 7 and PHP 8.1.17

**Comment by tvdijen** [comment] 2023-04-05 11:04
Do you get this message:

```
simplesamlphp/composer-module-installer contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "simplesamlphp/composer-module-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?]
```

And are accepting this?

**Comment by krisskals** [comment] 2023-04-05 11:17
Oh yes. I selected the no option. It is already working properly! Thank you for your help and for solving the problem 👍

**Comment by tvdijen** [comment] 2023-04-05 13:57
🤦🏻‍♂️ Glad we finally sorted this out

**Closed by tvdijen** 2023-04-05 13:57 UTC
Labels: needsinfo
