### ISSUE TITLE
Warning on single logout callback

### ISSUE THREAD

**Issue by bartv2** [simplesamlphp/simplesamlphp#134] opened 2014-12-03 13:17 UTC
The change introduced with ff177456 gives a warning in SAML2_Message:
```E_WARNING: DOMElement::setAttribute() expects parameter 2 to be string, array given````

This happens when the SingleLogoutService is configured with an array, for example with a Binding/Location combo.

**Comment by jaimeperez** [comment] 2015-01-15 13:32
Hi @bartv2!

Could you please provide some more info (i.e.: your configuration, a stack trace, log messages, etc)? I've been taking a look into this and I'm unable to reproduce that problem. Initially I thought it might be a problem with the bindings configured, as if the SOAP binding is used then the `$dst` variable is not mapped to the location. However, only HTTP-Redirect or HTTP-POST bindings will be allowed, so there's no way to reach that point with a SOAP binding. So what I think might be the problem actually is that the _SingleLogoutService_ is wrongly configured and the _Location_ parameter is an array instead of a string with the location itself.

**Comment by jaimeperez** [comment] 2015-08-12 08:11
Hi again @bartv2,

Since there's been no more information during the last 8 months and I'm unable to reproduce the issue, I'm closing it for now. Feel free to comment and ask for it to be reopened if necessary.

**Closed by jaimeperez** 2015-08-12 08:11 UTC
Labels: needsinfo
