### ISSUE TITLE
Azure active directory not working in google chrome web browser.

### ISSUE THREAD

**Issue by sheldonanto** [simplesamlphp/simplesamlphp#1444] opened 2021-03-18 10:31 UTC
I have used a simple saml application for Azure active directory SSO using SAML configuration.
when I try to login using chrome browser it is not working. but when I try to use a different browser it is working (firebox and etc).

**Describe the bug**
Simple saml successfully redirected to Microsoft login page after giving the user name and password. it does not give the excepted result. The URL SAMLRequest value is changed dynamically and continuously but never return the result 
"SAMLRequest={value}"

[SimpleSAMLphp - SSO Azure works in Firefox and Safari, but not in Chrome and Edge
](https://stackoverflow.com/questions/66031201/simplesamlphp-sso-azure-works-in-firefox-and-safari-but-not-in-chrome-and-edg) @tvdijen  @jaimeperez

**Comment by tvdijen** [comment] 2021-03-18 12:49
Handling of sameSite cookies _has_ changed between 1.18.8 and 1.19.0, so this could be part of the problem.. However, I'm unable to reproduce this..  Can you show me what flags the cookies have on your SimpleSAML-box? I'd like to compare them with my setup:

![afbeelding](https://user-images.githubusercontent.com/841045/111628718-d1ff4380-87f0-11eb-9a6d-033335be7ba6.png)

**Comment by sheldonanto** [comment] 2021-03-22 05:22
yes. you are correct the SimpleSAML version 1.18.8 works on all browser including chrome and edge. I have already configured the 1.18.8 version in my environment. so I can't able to reproduce this issue again. sorry about that. can you please look into this issue? please don't close it before resolve.

Many thanks.

**Comment by tvdijen** [comment] 2021-03-22 08:23
I can't look into this, because as I said, I can't reproduce it..

**Comment by thijskh** [comment] 2021-03-22 10:42
This is indeed most likely a SameSite cookie configuration issue. You should debug this yourself in your test environment.

**Comment by northway** [comment] 2021-03-24 13:42
I tried this one and worked: https://stackoverflow.com/questions/61917137/simplesamlphp-infinite-login-loop-once-again

Add the following line into the `config.php`:

```
'session.cookie.samesite' => strpos($userAgent, 'Chrome/') === false ? null : 'None',
```

**Comment by northway** [comment] 2021-03-24 13:53
I was only able to reproduce this error, when there was somekind of a discovery service in between (eduGAIN).

Without a discovery service, it works.

**Comment by tvdijen** [comment] 2021-03-24 15:25
@northway What version of Chrome are you using?

**Comment by northway** [comment] 2021-03-24 15:27
`Version 89.0.4389.90 (Official Build) (x86_64)`

**Comment by joernclausen** [comment] 2021-03-24 15:30
As discussed in

https://groups.google.com/g/simplesamlphp/c/bfDTlPMqq1w

the solution (or at least *a* solution) is to set
```
'session.cookie.secure' => true
```

**Comment by tvdijen** [comment] 2021-03-24 15:32
Yes, some browsers have additional requirements like setting the secure-flag for sameSite to work correctly.
@pradtke Do you perhaps see room for improvement to your earlier PR?

**Comment by tvdijen** [comment] 2021-03-24 15:36
@joernclausen Regarding the JS-issue.. Are you using the old or the new UI?

**Comment by joernclausen** [comment] 2021-03-24 15:49
> @joernclausen Regarding the JS-issue.. Are you using the old or the new UI?

Could you elaborate? The UI of SSP? There is an old and a new one??? You've completely lost me :)

**Comment by tvdijen** [comment] 2021-03-24 16:05
Yes there is, but it's kind of a hidden feature so far ;)
If in `config.php` you insert `usenewui => true` magical things will happen.  Besides the new looks, we've moved from .tpl.php files to Twig templates.  I now know you are on the old UI, so I know where to start looking for differences between 1.18.8 and 1.19.0. Thanks!

**Comment by pradtke** [comment] 2021-03-24 16:17
> Yes, some browsers have additional requirements like setting the secure-flag for sameSite to work correctly.
> @pradtke Do you perhaps see room for improvement to your earlier PR?

I suppose we could log a warning if `sameSite = 'None'` and secure is not enabled. That may make it easier for people to self diagnose.  I think making the default `session.cookie.secure`=true in config-template may also help for people that copy-n-paste from there.

**Comment by tvdijen** [comment] 2021-03-24 16:20
I agree @pradtke ! That setting should be secure by default!  nobody in their right mind should run an IDP on http anyway..

**Comment by tvdijen** [comment] 2021-03-24 16:57
@joernclausen I'm interested if setting `usenewui=>true` makes a difference in the JS-issue... I've checked and the JS-part is still the same in 1.19, also the .tpl.php template is the same...  It's really strange if you ask me.

**Comment by joernclausen** [comment] 2021-03-25 09:52
Nope, the JS-issue is still present...

My `config.php` now starts with
```
$config = [
  'usenewui' => true,
```

When I open the URL of the SP, which would have led me to the SSP dashboard before, I am immediately redirected to my IdP. When I provide correct credentials, I return to SSP (with red design, I guess this is the new UI), but I still need to press the "Continue" button before. I see some debug information (SAML attributes, SAML Subject), but all other links are gone (e.g. status of SSP, EntityID converter). Are they now accessible under a new URL?

I think it is not really worth the effort to debug this further: If no one can reproduce it, if we agree that JavaScript is nowadays a necessity, and - most importantly - the problem of the OP (and mine) is solved, I guess it's okay to close this issue. If I ever feel the need to tackle the JS thingy again, I'll open a new one :)

**Comment by tvdijen** [comment] 2021-03-25 11:04
Under the new UI (indeed the red theme) some things have been moved..
What you are looking for is probably under /admin

**Closed by tvdijen** 2021-03-25 11:04 UTC
