### ISSUE TITLE
metadata-converter.php not working correctly anymore

### ISSUE THREAD

**Issue by kbabioch** [simplesamlphp/simplesamlphp#940] opened 2018-09-26 08:44 UTC
I'm running simpleSAMLphp (php-fpm & Apache). Before upgrading to the latest version `1.16.1`, I was running `1.15.4`. Back then I was able to use the metadata converter to convert my XML metadata into simpleSAMLphp's own format.

After the upgrade, this seems to no longer work. When putting the XML file into the text field and/or uploading it, the request takes a long time to process and will finally quit with a `503` error.

After going through the log files for a bit, I found messages like this:

	Sep 26 10:25:54 simplesamlphp ERROR [f27747020a] SimpleSAML_Error_Exception: Error 2 - DOMDocument::schemaValidate(http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd): failed to open stream: HTTP request failed! 
	Sep 26 10:25:54 simplesamlphp ERROR [f27747020a] Backtrace:
	Sep 26 10:25:54 simplesamlphp ERROR [f27747020a] 4 /srv/www/testidp/simplesamlphp/www/_include.php:58 (SimpleSAML_error_handler)
	Sep 26 10:25:54 simplesamlphp ERROR [f27747020a] 3 [builtin] (DOMDocument::schemaValidate)
	Sep 26 10:25:54 simplesamlphp ERROR [f27747020a] 2 /srv/www/testidp/simplesamlphp/lib/SimpleSAML/Utils/XML.php:437 (SimpleSAML\Utils\XML::isValid)
	Sep 26 10:25:54 simplesamlphp ERROR [f27747020a] 1 /srv/www/testidp/simplesamlphp/lib/SimpleSAML/Utils/XML.php:69 (SimpleSAML\Utils\XML::checkSAMLMessage)
	Sep 26 10:25:54 simplesamlphp ERROR [f27747020a] 0 /srv/www/testidp/simplesamlphp/www/admin/metadata-converter.php:16 (N/A)
	Sep 26 10:27:54 simplesamlphp ERROR [f27747020a] SimpleSAML_Error_Exception: Error 2 - DOMDocument::schemaValidate(http://www.w3.org/TR/2002/REC-xmlenc-core-20021210/xenc-schema.xsd): failed to open stream: HTTP request failed! 

So, it seems that something about the schema validation has changed between those versions. Not sure if this was already required before, but I enabled `allow_url_fopen` and `allow_url_include` now, but the issue still remains.

Everything else in this setup seems to work just fine - as far as I can tell.

**Comment by tvdijen** [comment] 2018-09-26 09:29
I think in 1.15 the schemas were never checked because of a bug: https://github.com/simplesamlphp/simplesamlphp/commit/7458ecf280f7e4261b17ce650dedd5f96502c370

This can probably be fixed if we replace the external references to schemas with local files here (and include them in the release):
https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.16/schemas/saml-schema-metadata-2.0.xsd#L14-L16

@kbabioch would you be able to test this for me?

**Comment by kbabioch** [comment] 2018-09-26 09:39
I'm more than happy to test, but don't quite get what to do here. Is there a specific commit you can point me to, or should I patch the code myself? As said in the other bug, loading external references is not really the way to go, so we should have those files locally. In this case also don't need to fiddle arround with `allow_url_fopen` and `allow_url_include`, which in itself are security concerns.

**Comment by tvdijen** [comment] 2018-09-26 09:44
Sorry if I'm being unclear. Haven't had my regular dose of cafeïne yet ;)

Could you download http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd and http://www.w3.org/TR/2002/REC-xmlenc-core-20021210/xenc-schema.xsd to the schemas-directory and then replace the external url's [here](https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.16/schemas/saml-schema-metadata-2.0.xsd#L14-L16) with just their local filenames?

**Comment by tvdijen** [comment] 2018-09-26 09:44
Or, as an alternative, provide me with a metadata-file that allows me to reproduce this (since I haven't been able to so far)

**Comment by jaimeperez** [comment] 2018-09-26 09:54
Maybe I am missing something here, but schema validation shouldn't be happening by default. @kbabioch, do you have this configuration enabled (set to `true`)?

```php
$config['debug']['validatexml'];
```

@tvdijen I think that config option should default to false. If it doesn't or SSP doesn't honor it, then there's something wrong here.

**Comment by kbabioch** [comment] 2018-09-26 09:57
Yes, I have `validatexml` set to true and have done so manually (but forgot in the meantime ;)). @tvdijen Maybe when enabling this, you can re-produce the bug? Otherwise I'm more than happy to provide you the metadata I'm using here.

**Comment by tvdijen** [comment] 2018-09-26 10:06
Ah, that I missed.. I can reproduce it now..
@jaimeperez do you agree that those schema files should be local files?

**Comment by jaimeperez** [comment] 2018-09-26 10:09
Yes, of course. As @pmeulen was saying in #894, no schemas should ever be loaded from remote locations. But... aren't they local already? Why is validation becoming a problem now?

**Comment by tvdijen** [comment] 2018-09-26 10:13
Nope, there are at least three being referenced [externally](https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.16/schemas/saml-schema-metadata-2.0.xsd#L14-L20)...
Like I said, validation probably never worked due to a [bug](https://github.com/simplesamlphp/simplesamlphp/commit/7458ecf280f7e4261b17ce650dedd5f96502c370) that messed up the path to the schema, which was fixed recently..

**Comment by jaimeperez** [comment] 2018-09-26 10:20
I see, it looks like I introduced that extra dot accidentally about a year ago 😞 But actually, that means validation should have worked before. At least I'm pretty certain it used to work.

In any case, yeah, we should fix the external references ASAP...

**Comment by jaimeperez** [comment] 2018-09-26 10:29
Wonderful! Thanks so much Tim!

**Comment by tvdijen** [comment] 2018-09-26 10:32
Fixed on both master and 1.16

**Closed by tvdijen** 2018-09-26 10:32 UTC

**Comment by kbabioch** [comment] 2018-10-02 11:29
Just as a point of reference: I can confirm this is working now in 1.16.2.
